### ISSUE TITLE
[Bug]: Inconsistent behavior on ipv4/ipv6 flag for linode_firewall resource

### ISSUE THREAD

**Issue by securitylevelup** [linode/terraform-provider-linode#1003]
### Terraform Version

Terraform v1.5.2 on darwin_arm64

### Linode Provider Version

v2.7.1

### Effected Terraform Resources

linode_instance
https://registry.terraform.io/providers/linode/linode/latest/docs/data-sources/instances#ip_address
https://registry.terraform.io/providers/linode/linode/latest/docs/data-sources/instances#ipv4
https://registry.terraform.io/providers/linode/linode/latest/docs/data-sources/instances#ipv6

### Expected Behavior

ipv4 and ip_address output both do not contain the subnet mask. ipv6 output does contain the subnet mask. This is inconsistent. Can subnet mask be added to at least the ipv4 output?

### Actual Behavior

see above

### Steps to Reproduce

generate a linode_instance, verify the ipv4/ipv6/ip_adddress flags in TF state.

**Comment by aslepcev** [comment]
Example: 

resource "linode_firewall" "myfw" {
  label = "Allow SSH"

  inbound {
    label     = "ssh"
    action    = "ACCEPT"
    protocol  = "TCP"
    ports     = "22"
    ipv6      = ["linode_instance.myserver.ipv6"] - works since it contains the mask
    ipv4      = ["linode_instance.myserver.ipv4"] - doesn't work since it doesn't contain the mask
   }   

  inbound_policy = "DROP"
  outbound_policy = "ACCEPT"

  linodes = [linode_instance.some_server.0.id]
}

**Comment by lgarber-akamai** [comment]
Hello, thanks for the report!

As of now we do not have plans to expose the CIDR suffix directly through the linode_instance `ipv4` and `ip_address` fields as this could potentially cause a breaking change. Given these IPv4 addresses should all be single IP allocations, you should be able to add a `/32` suffix your instance’s IPv4 address when configuring Firewall rules.

Please let us know if you have any other feature requests or run into any other issues 🙂
