### ISSUE TITLE
[Feature]: #cloud-config support

### ISSUE THREAD

**Issue by johnstonmatt** [linode/terraform-provider-linode#1038]
### Description

The top 3 major public clouds (and many more!) have standardized on using `#cloud-config` files to setup a vm when it boots. I understand Linode has a similar feature in "stack_script" but this is not a well-known and commonly implemented standard.

My team is building software at [github.com/polyseam/cndi](https://github.com/polyseam/cndi) and we would like to provide support for deploying to Linode, but this missing feature prevents us from doing so easily and reliably.

### New or Affected Terraform Resources

linode_instance

### Potential Terraform Configuration

`linode_instance.user_data` : - (Optional) User data to provide when launching the instance

more details: https://cloudinit.readthedocs.io/

**Comment by zliang-akamai** [comment]
Hey @johnstonmatt, thanks for reporting it!

I think the user data of `cloud-init`, which is the content of `cloud-config`, is supported by [Akamai Metadata service](https://www.linode.com/docs/products/compute/compute-instances/guides/metadata/). We also included the `metadata` attribute in our Terraform [`linode_instance` resource](https://github.com/linode/terraform-provider-linode/blob/9772b2b39fb134ec0b549f121f6446d43cf90c17/linode/instance/schema_resource.go#L32).

Does it solve your concern? Let us know if you have any other question.

**Comment by johnstonmatt** [comment]
This sounds like exactly what I was looking for! Would you be able to point me to the documentation for the feature in the terraform registry if it exists?

**Comment by zliang-akamai** [comment]
Hi @johnstonmatt
We are still preparing the document, and I will let you know when it's ready (should be pretty soon).

**Comment by johnstonmatt** [comment]
awesome, thanks!
