### ISSUE TITLE
[Bug]: Lifecycle attribute stop plan execution

### ISSUE THREAD

**Issue by gesker** [linode/terraform-provider-linode#1059]
### Terraform Version

Terraform 1.5.7 on Debian Stable

### Linode Provider Version

version = "2.9.0"

### Effected Terraform Resources

linode_domain

### Terraform Config Files

Demonstrator at:

https://github.com/gesker/bugdemonstrator00

Short version...

```
resource "linode_domain" "mydomain" {
  type        = "master" # Ignore DNS records at external, REGISTRAR NS records point to Linode
  domain      = var.domain_name_mydomain_com
  soa_email   = var.domain_soa_email
  tags        = ["mydomain"]
  description = var.domain_name_mydomain_com

  ttl_sec     = var.domain_default_ttl_sec
  refresh_sec = var.domain_default_refresh_sec
  retry_sec   = var.domain_default_retry_sec
  expire_sec  = var.domain_default_expire_sec

  lifecycle {
    prevent_destroy = true  **# Stops destroy for entire project**
  }

}
```

### Panic Output

Not panic just error:

```
│ Error: Instance cannot be destroyed
│ 
│   on linode_dns.tf line 2:
│    2: resource "linode_domain" "mydomain" {
│ 
│ Resource linode_domain.mydomain has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue with the plan, either disable
│ lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.



```

### Expected Behavior

Resources should be destroyed. This resource(s) with lifecycle - prevent_destroy should remain.

### Actual Behavior

Plan is stopped for entire project.

### Steps to Reproduce

1. Clone demonstrator [here](https://github.com/gesker/bugdemonstrator00).
2. Add entries to terraform/backend.cfg 
3. Add good info where **REDACTED** in terraform/terraform.tfvars
4. make tf_full_reset 
5. make tf_destroy

Steps 2 and 3 above are just because I removed passwords, tokens, etc.

**Comment by amisiorek-akamai** [comment]
Hi @gesker, thanks for reporting on this issue! After taking a look, it seems like this behavior is caused on Terraform's end. `prevent_destroy`, when set to true, will cause Terraform to reject with an error any plan that would destroy the infrastructure object associated with the resource, as long as the argument remains present in the configuration. I think the fix would have to come from the other part of the error message, where Terraform says to either disable `prevent_destroy` or reduce the scope of the plan.

Let me know if this helps! You can also find more information on the usage of `prevent_destroy` here:
[https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#prevent_destroy](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#prevent_destroy)

**Comment by gesker** [comment]
No. Just running apply a second time.

**Comment by gesker** [comment]
Uggh. You are right.

Would you happen to know if Terraform will implement an ignore_destroy at some point or add an option to ignore_changes to protect certain resources within a Terraform project?

Use case being an instance may need to be reset but storage (of some kind) or other resource that needs to stay up (DNS) should be untouched?

**Comment by amisiorek-akamai** [comment]
No, unfortunately, we do not have contact with Terraform. You can try putting in an issue on their repository, but again, we will not be able to do anything on our end.

**Comment by jriddle-linode** [comment]
Closing as it comes from Terraform itself, if you find a issue with the provider causing this let us know.
