### ISSUE TITLE
[Bug]: Cannot RE-allocate storage

### ISSUE THREAD

**Issue by gesker** [linode/terraform-provider-linode#1060]
### Terraform Version

Terraform 1.5.7 on Debian Stable

### Linode Provider Version

version = "2.9.0"

### Effected Terraform Resources

linode_instance_config
linode_instance_disk
linode_instance

### Terraform Config Files

Demonstrator at:
https://github.com/gesker/bugdemonstrator01

Short version...

```terraform
resource "linode_instance_config" "cfg_instance_config" {
  count = var.cfg_node_count
  label = "cfg-instance-config-${count.index}"
  linode_id = linode_instance.cfg_instance[count.index].id

  booted = true

  devices {
    sda {
      disk_id = linode_instance_disk.cfg_instance_boot[count.index].id  # Second Apply Fails
    }
  }

#  interface {
#    purpose = "public"
#  }
#
#  interface {
#    purpose = "vlan"
#    label = "my-vlan"
#    ipam_address = "10.0.1.${count.index}/24"
#  }


}
```

### Panic Output

Not panic just error:

```
│ Error: failed to create linode instance disk: [400] [size] You do not have enough unallocated storage to create this Disk.
│ 
│   with linode_instance_disk.cfg_instance_boot[0],
│   on linode_instance_cfg.tf line 1, in resource "linode_instance_disk" "cfg_instance_boot":
│    1: resource "linode_instance_disk" "cfg_instance_boot" {
│ 
╵

```

### Expected Behavior

Resource should be reapplied with out error

### Actual Behavior

Unallocated storage error

Deleteing the instance via the web ui and then reapplying allows the terraform routines allows the plan to move forward.

### Steps to Reproduce

1. Clone demonstrator [here](https://github.com/gesker/bugdemonstrator01).
2. Add entries to terraform/backend.cfg 
3. Add good info where **REDACTED** in terraform/terraform.tfvars
4. make tf_full_reset 
5. make tf_apply  -- **this is a SECOND apply is where failure occurs**

Steps 2 and 3 above are just because I removed passwords, tokens, etc.

**Comment by amisiorek-akamai** [comment]
Hi @gesker, thanks for reporting on this issue! Are you removing the other storage device before attempting to create the other one? It looks like the error generated is coming from your account as opposed to the Terraform provider.

**Comment by gesker** [comment]
Happens on second apply
May or may not be related but I did notice that destroying/provisioning using device/devices seems to take longer. Just a data point.

**Comment by amisiorek-akamai** [comment]
How much time is in between tf_full_reset and tf_apply? There's a chance that the device is still in the process of being removed after running tf_apply.

**Comment by gesker** [comment]
couple of hours

**Comment by amisiorek-akamai** [comment]
I see, we'll take a better look at this issue and let you know of any updates.

**Comment by lattwood** [comment]
Check the allocated storage on the instance in the Linode UI. I worked around this by only ever allocating half the storage on a linode.

**Comment by zliang-akamai** [comment]
Hi @gesker, I think you would need to simply remove `image`, `authorized_keys`, and `root_pass` from the `linode_instance` resource named `cfg_instance`.

If you specify these attributes on a `linode_instance` resource, Linode will implicitly create a disk with a config alongside with the `linode_instance` resource, which cause no space left for an additional disk to be created with a `linode_instance_disk` resource on a Linode.
