### ISSUE TITLE
[Bug]: VLAN not Applied Completely

### ISSUE THREAD

**Issue by gesker** [linode/terraform-provider-linode#1061]
### Terraform Version

Terraform 1.5.7 on Debian Stable

### Linode Provider Version

version = "2.9.0"

### Effected Terraform Resources

linode_instance_config
linode_instance

### Terraform Config Files

Demonstrator at:
https://github.com/gesker/bugdemonstrator02

Short version...

```
resource "linode_instance_config" "cfg_instance_config" {
  count = var.cfg_node_count
  label = "cfg-instance-config-${count.index}"
  linode_id = linode_instance.cfg_instance[count.index].id

  booted = true

  devices {
    sda {
      disk_id = linode_instance_disk.cfg_instance_boot[count.index].id  # Second Apply Fails
    }
  }

  interface {
    purpose = "public"
  }

  interface {
    purpose = "vlan"
    label = "my-vlan"
    ipam_address = "10.0.1.${count.index}/24"
  }


}
```

### Panic Output

No errors are reported on plan execution

### Expected Behavior

A second interface eth1 would be added to the linode_instance with a 10.x.x.x ip address

### Actual Behavior

The configuration is only partially applied.
It is visible in the WebUI at 
Linodes --> cfg-instance-0 --> Configurations

BUT...

The interfaces is NOT found at:
Linodes --> cfg-instance-0 --> Network

Issuing `ip address` within the linode_instance also returns only eth0 instead of eth0 and eth1

### Steps to Reproduce

1. Clone demonstrator [here](https://github.com/gesker/bugdemonstrator02).
2. Add entries to terraform/backend.cfg 
3. Add good info where **REDACTED** in terraform/terraform.tfvars
4. make tf_full_reset 

ssh into instance and issue `ip address`

Steps 2 and 3 above are just because I removed passwords, tokens, etc.

**Comment by gesker** [comment]
It does not.

Do you have an ETA when the IPAM will show in the networking section?

Also, what is the correct way to reference the ipam from the instance so
that this vlan address value can be used elsewhere in terraform scripts?
E.g. creating an ansible inventory.
linode_instance.my_instance[*].vlan_address ???

Thanks,
Dennis

**Comment by amisiorek-akamai** [comment]
Unfortunately, we do not have an ETA, but we can let you know of any updates. To answer your second question, you can access the IPAM by using `linode_instance_config.my_instance.interface.0.ipam_address`.

**Comment by jriddle-linode** [comment]
We've created a feature request for this request to our API team. We're closing this here as its out of scope for the terraform provider.
