### ISSUE TITLE
[Bug]: Public Interface NOT ALWAYS eth0

### ISSUE THREAD

**Issue by gesker** [linode/terraform-provider-linode#1062]
### Terraform Version

Terraform 1.5.7 on Debian Stable

### Linode Provider Version

version = "2.9.0"

### Effected Terraform Resources

linode_instance
linode_instance_configuration

### Terraform Config Files

```
resource "linode_instance_config" "cfg_instance_config" {
  count = var.cfg_node_count
  label = "cfg-instance-config-${count.index}"
  linode_id = linode_instance.cfg_instance[count.index].id

  booted = true

  devices {
    sda {
      disk_id = linode_instance_disk.cfg_instance_boot[count.index].id
    }
  }

  interface {
    purpose = "vlan"
    label = "my-vlan"
    ipam_address = "10.0.1.${count.index}/24"
  }
  
  interface {
    purpose = "public"  ## Configuration assigned eth1 to public - docs indicate should be eth0
  }


}
```

### Debug Output

None.

### Panic Output

None.

### Expected Behavior

Public interface should be eth0

### Actual Behavior

Public interface should be eth1

### Steps to Reproduce

Apply a linode_instance_config where "vlan" is indicated BEFORE interface for with purpose "public"
The order the interface appears in the linode_instance_config SEEMS to drive the ethX number.

Perhaps a "ethNumber" or "eth_order"  could be added tot he interface attribute so that there is no guess work in which network interface will be used for which purpose?

**Comment by gesker** [comment]
Could this be flipped to a feature request allowing / requiring the interface to be specified - not unlike device?

**Comment by amisiorek-akamai** [comment]
Sure, we will let you know of any updates!
