### ISSUE TITLE
[Feature]: Project Isolation

### ISSUE THREAD

**Issue by gesker** [linode/terraform-provider-linode#1063]
### Description

It would be very nice if terraform projects could be "isolated" in some fashion in order to prevent conflicts/collision of resources indicated in one terraform project with those in a second project.

Perhaps, in the linode **provider** an attribute of "project_name" could be added. This "project_name" could serve as a PREFIX to any and all resources created within a terraform project.

### New or Affected Terraform Resources

Linode Provider
Maybe, Web UI could leverage the project_name and display folders.

### Potential Terraform Configuration

Project  "first" might look like...

```
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
    }
  }
}

# Configure the Linode Provider
provider "linode" {
  project_name = "first"
}

resource "linode_instance" "foobar" {
  # ...
}
```

Project "second" might look like...

```
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
    }
  }
}

# Configure the Linode Provider
provider "linode" {
  project_name = "second"
}

resource "linode_instance" "foobar" {
  # ...
}
```

Within Linode the resouces would look like...

first_foobar
second_foobar

**Comment by gesker** [comment]
At the very least this would be helpful in organizing resources and would provide some visual clues in the WebUI.

**Comment by amisiorek-akamai** [comment]
Hi @gesker, thanks for the suggestion! Unfortunately, we cannot implement this feature at the moment. However, your suggestion is being handled internally and we will let you know when we have any updates.

**Comment by gesker** [comment]
That would be great. Thanks @amisiorek-akamai
