### ISSUE TITLE
[Feature]: swap_size Attribute on linode_instance_disk

### ISSUE THREAD

**Issue by gesker** [linode/terraform-provider-linode#1064]
### Description

If one specifies a swap_size directly in the linode_instance - not using the linode_instance_config approach - the boot partition size is automatically calculated to be the maximum size available less the indicated swap space.

While the linode_instance_config allows one to specify multiple linode_instance_disks - both a boot disk and a swap disk can be specified as in the documentation - there doesn't seem to be a mechanism for automatically maximizing the storage space that is by default available to the NON-swap disk so as to maximize the pre-allocated storage available to the node. So, one could easily under specify storage available to the "type" of node or over allocate and receive and error.

Being able to indicate a swap space on a linode_instance_disk that would appear within the node as a second partition would be a way to address this and allow the behavior to be more like it is presently when specifying swap_size directly in linode_instance

### New or Affected Terraform Resources

linode_instance_disk

### Potential Terraform Configuration

```
resource "linode_instance_disk" "boot" {
  label = "boot"
  linode_id = linode_instance.my-instance.id
  size = 512
  filesystem = "ext4"

# Swap partition would appear as /dev/sd(n..)2 e.g. /dev/sda2 or /dev/sdb2 with label "swap"
swap_partition { 
 swap_size = 4096
}

}
```

**Comment by amisiorek-akamai** [comment]
Hi @gesker, thanks for the suggestion! Unfortunately, we cannot implement this feature at the moment. However, your suggestion is being handled internally and we will let you know when we have any updates.
