### ISSUE TITLE
[Bug]: Docs: `linode_database_access_controls` resource missing from docs starting v2.9.0

### ISSUE THREAD

**Issue by NominalTrajectory** [linode/terraform-provider-linode#1084]
### Terraform Version

v1.0.10

### Linode Provider Version

v2.9.0

### Effected Terraform Resources

linode_database_access_controls

### Expected Behavior

The `linode_database_access_controls` should be listed in the docs.

### Actual Behavior

The `linode_database_access_controls` is not listed in the docs.

I looked through the releases, and this became an issue starting at `v2.9.0` which I suspect is related to https://github.com/linode/terraform-provider-linode/pull/1040

### Steps to Reproduce

1. Open https://registry.terraform.io/providers/linode/linode/2.9.2/docs/resources/database_access_controls
2. Get 404

**Comment by jriddle-linode** [comment]
Thank you for the report I've created a ticket to track this and we'll get back to you once we've resolved it.
