### ISSUE TITLE
Visual Studio Code Terraform failed to load plugins

### ISSUE THREAD

**Issue by JamieC456** [linode/terraform-provider-linode#1099]
### Terraform Version

Terraform v1.6.2 on windows_amd64

### Linode Provider Version

version = "2.9.3"

### Effected Terraform Resources

provider registry.terraform.io/linode/linode v2.9.3

### Terraform Config Files

terraform {
  required_providers {
    linode = {
      source = "linode/linode"
      version = "2.9.3"
    }
  }
}

#Configure the Provider

provider "linode"{
  token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}

#Create a Linode

resource "linode_instance" "Plex-Terraform-eu-west" {
    image = "linode/debian11"
    label = "eu-west"
    group = "Media-Server"
    region = "eu-west"
    type = "g6-standard-1"
    root_password = "XXXXXXXXXXXXX"
}

### Expected Behavior

terraform initialize the planned infrastructure

### Actual Behavior

Error: Failed to load plugin schemas
│
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load    
│ the schema for provider registry.terraform.io/linode/linode: failed to retrieve schema from provider   
│ "registry.terraform.io/linode/linode": Plugin did not respond: The plugin encountered an error, and    
│ failed to respond to the plugin.(*GRPCProvider).GetProviderSchema call. The plugin logs may contain    
│ more details...

### Steps to Reproduce

terraform init
terraform plan

when using visual studio code

**Comment by jriddle-linode** [comment]
We've created a internal ticket to track this and will update you once we have more information.

**Comment by lgarber-akamai** [comment]
Hi @JamieC456, thanks for the report!

Since it looks like you were able to resolve this problem in [this community post](https://www.linode.com/community/questions/24515/terraform-cannot-find-provider) I'll go ahead and close this issue. If you're still running into this issue or you feel this issue is a provider bug, feel free to @ me 🙂
