### ISSUE TITLE
[Bug]: Deprecated parameters used in examples

### ISSUE THREAD

**Issue by lattwood** [linode/terraform-provider-linode#1109]
### Terraform Version

N/A

### Linode Provider Version

"latest"

### Effected Terraform Resources

linode_instance_config

### Expected Behavior

I would expect the docs don't use deprecated config parameters in their examples.

### Actual Behavior

They do.

### Steps to Reproduce

Go to this page: https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance_config

See the examples use `devices`.

See further down the page it says it's deprecated in favour of `device` blocks.

**Comment by zliang-akamai** [comment]
Hi 👋 @lattwood, thanks for bringing this to our attention! We are aware of the issue and currently working on the documentation.
