### ISSUE TITLE
[Bug]: API request to determine instance types failing

### ISSUE THREAD

**Issue by BraveHelyx** [linode/terraform-provider-linode#1117]
### Terraform Version

Terraform 1.6.2 on AMD64

### Linode Provider Version

2.9.5

### Effected Terraform Resources

provider

### Terraform Config Files

```
terraform {
    required_providers {
        linode = {
            source = "linode/linode"
            version = "2.9.5"
        }
    }
}

provider "linode" {
    token = "<REDACTED>"
}

resource "linode_instance" "terraform-ssh" {
    type = "g6-nanode-1"
    region = "ap-southeast"
    image = "linode/arch"
    group = "Terraform"
    authorized_keys = [ "<REDACTED>" ]
    root_pass = "ASDFASDFASDF"
}

```

### Debug Output

│ Error: Error connecting to the Linode API: [002] Get "https://api.linode.com/v4/linode/types?page=100": dial tcp [2600:3c00::23]:443: connect: network is unreachable
│ 
│   with provider["registry.terraform.io/linode/linode"],
│   on provider.tf line 10, in provider "linode":
│   10: provider "linode" {

### Expected Behavior

Expected a standard `terraform apply` workflow.

### Actual Behavior

Terraform fails to submit a request to https://api.linode.com/v4/linode/types?page=100 

I believe this is due to an invalid `page` parameter/value. As far as I am aware, the requested URL is defined by the provider version. 

`curl https://api.linode.com/v4/linode/types?page=100` returns an empty data field as shown:

```
{
  "data": [],
  "page": 100,
  "pages": 1,
  "results": 37
}
```

Setting the provider version to a legacy version fixes this issue (Tested using 1.26.0). This bug also affects 2.9.4.

### Steps to Reproduce

1. In an empty directory create `main.tf`

```
terraform {
    required_providers {
        linode = {
            source = "linode/linode"
            version = "2.9.5"
        }
    }
}

provider "linode" {
    token = "<REDACTED>"
}

resource "linode_instance" "terraform-ssh" {
    type = "g6-nanode-1"
    region = "ap-southeast"
    image = "linode/arch"
    group = "Terraform"
    authorized_keys = [ "<REDACTED>" ]
    root_pass = "ASDFASDFASDF"
}

```

2. Run `terraform init`
3. Run `terraform plan`
4. Run `terraform apply`

**Comment by zliang-akamai** [comment]
Hi @BraveHelyx, thanks for reporting the issue!

I think this is an intermittent networking issue which we can't do much about, and I was unable to reproduce the issue from my end.

Maybe you can try changing the network environment like restarting your WiFi router or retrying it after a few hours?

**Comment by zliang-akamai** [comment]
Hi @BraveHelyx,
After a further investigation, @lgarber-akamai found this is an intentional API call to get an empty response to verify the token is valid.
https://github.com/linode/terraform-provider-linode/blob/dev/linode/provider.go#L257-L259

Your Terraform error seems to be an intermittent networking issue. Maybe you can try restart your WiFi router or change a networking environment to see if it's fixed?
