### ISSUE TITLE
[Feature]: Docs for VLANs

### ISSUE THREAD

**Issue by adrianteri** [linode/terraform-provider-linode#1138]
### Description

Can docs in provider have cautions/warnings when creating VLANs under *interface*?

I've battled close to a week what I thought was a bug but support indicated I didn't declare a **public** interface in my resource blocks.

Today, getting some background from issues, found out at some point the **order** mattered with which interfaces were declared and created #508. Confirmed it's not the case today...

Also recently from #1062 it seems there are inconsistencies on the order you declare interfaces and how they are created and/or associated.
From testing #508 above I've declared a public interface as **second**(just like the author of #1062) however the interface is assigned to/gets `eth0` instead of `eth1`. The author of the issue indicates it's the direct opposite for them!

From [API docs](https://www.linode.com/docs/api/linode-instances/#configuration-profile-create) it's documented that for instances to be reached **publicly** `eth0` must be a public interface.

![image](https://github.com/linode/terraform-provider-linode/assets/10687877/413eeea3-79c7-408f-b3ec-a4c55496d806)

### New or Affected Terraform Resources

linode_instance

### Potential Terraform Configuration

N/A

**Comment by lgarber-akamai** [comment]
Thanks for the suggestion! I've added a ticket to our internal tracker to improve the documentation around interface ordering.

**Comment by zliang-akamai** [comment]
Fixed in https://github.com/linode/terraform-provider-linode/pull/1194
