### ISSUE TITLE
[Bug]: StackScript creation error => You don't have permission to access "http://api.linode.com/v4/linode/stackscripts"

### ISSUE THREAD

**Issue by max-tremblay** [linode/terraform-provider-linode#1221]
### Terraform Version

v1.6.5

### Linode Provider Version

2.12.0

### Effected Terraform Resources

linode_stackscript

### Terraform Config Files
```terraform
resource "linode_stackscript" "example" {
  label       = "provision-example"
  description = "Provision the example"
  script      = <<EOT
#!/bin/bash
# https://raw.githubusercontent.com/
  EOT
  images      = ["linode/ubuntu20.04"]
}
```

### Expected Behavior

The stackscript should be created, but it fails if the script contains "https://raw.githubusercontent.com/" [the trailing slash needs to be present]

Removing the domain will allow the resource to be deployed.

### Actual Behavior

We're seeing a permission denied

### Steps to Reproduce

Just apply the example in that ticket.

**Comment by lgarber-akamai** [comment]
Thanks for the report! This is a known issue that is currently being addressed internally; I'll let you know when we have any updates 🙂

**Comment by lgarber-akamai** [comment]
This issue has been resolved, let us know if you run into any other issues 🙂
