### ISSUE TITLE
[Feature]: Support "force delete" for bucket

### ISSUE THREAD

**Issue by mzimry** [linode/terraform-provider-linode#1236]
### Description

we would like to delete a **non-empty** bucket using `terraform destroy` .

### New or Affected Terraform Resources

Linode bucket

### Potential Terraform Configuration

`resource "linode_object_storage_bucket" "project-bucket" {
    cluster     = var.bucket_cluster_id
    label       = var.bucket_name
    force_delete = true
}`

**Comment by zliang-akamai** [comment]
Hi @mzimry, thanks for the feature request! We already have a GitHub issue for this feature, and we are currently working on it.
https://github.com/linode/terraform-provider-linode/issues/1129

**Comment by mzimry** [comment]
hey @zliang-akamai , regarding this : https://github.com/linode/terraform-provider-linode/issues/1129
Thank you,  when is this feature expected to be released?
