### ISSUE TITLE
[Bug]: `group` attribute not being removed 

### ISSUE THREAD

**Issue by aleprovencio** [linode/terraform-provider-linode#1296]
### Terraform Version

Terraform v1.6.6 on linux_amd64

### Linode Provider Version

version = "2.14.0"

### Effected Terraform Resources

linode_instance

### Terraform Config Files

```terraform
resource "linode_instance" "example" {
  image           = "linode/debian12"
  label           = "aleprovencio-example"
  tags            = ["aleprovencio-example"]
  region          = "br-gru"
  type            = "g6-nanode-1"
  authorized_keys = [chomp(file("${var.ssh_publickey_path}"))]
  root_pass       = var.root_password
}
```

### Debug Output

No generated output

### Panic Output

No generated output

### Expected Behavior

`group` attribute being removed after `terraform apply`

### Actual Behavior

`terraform apply` indicates it will remove the `group` attribute and results in a changed attribute. However running it once again is like it was never removed

### Steps to Reproduce

- Remove `group` attribute from an existing instance
- Run `terraform apply` twice

**Comment by zliang-akamai** [comment]
Hi @aleprovencio,
Thanks for the bug report! As you may noticed, our work to fix it is in progress and the change is expected to come with the next release of the Terraform Provider for Linode.

**Comment by aleprovencio** [comment]
Yeah I've noticed your progress @zliang-akamai , thank you for taking this on
