### ISSUE TITLE
[Feature]: Add tags to LKE pool

### ISSUE THREAD

**Issue by programmigo** [linode/terraform-provider-linode#1336]
### Description

We would like to add tags not only LKE cluster, but also to pool that creates that cluster

### New or Affected Terraform Resources

linode_lke_cluster

### Potential Terraform Configuration

```
resource "linode_lke_cluster" "my-cluster" {
    label       = "my-cluster"
    k8s_version = "1.28"
    region      = "us-central"
    tags        = ["prod"]

    pool {
        type  = "g6-standard-2"
        count = 3
        tags        = ["managed-by-terraform", "prod"]
    }
}
```

**Comment by programmigo** [comment]
Hi, I see work has been done in 2.17.0. Could you please add this version to terraform registry https://registry.terraform.io/providers/linode/linode/ ?

**Comment by programmigo** [comment]
@lgarber-akamai I've tried new version of this provider and we still can't define tags for the first pool that has to be defined on LKE cluster creation.
`linode_nodepool` can't be assigned as first pool to LKE cluster either.

```
resource "linode_lke_cluster" "my-cluster" {
    label       = "my-cluster"
    k8s_version = "1.28"
    region      = "us-central"
    tags        = ["prod"]

    pool {
        type  = "g6-standard-2"
        count = 3
        tags        = ["managed-by-terraform", "prod", "pool-tag"]
    }
}
```

**Comment by zliang-akamai** [comment]
Hi @programmigo,
While we are working on tag support within the legacy nested pool blocks, you may create a pool in the `linode_lke_node_pool` resource like @lgarber-akamai mentioned.

Here is an example:
```terraform
locals {
  external_pool_tag = "external"
}

resource "linode_lke_node_pool" "my-pool" {
    cluster_id  = linode_lke_cluster.my-cluster.id
    type        = "g6-standard-2"
    node_count  = 3

    tags = [local.external_pool_tag]
}

resource "linode_lke_cluster" "my-cluster" {
    label       = "my-cluster"
    k8s_version = "1.28"
    region      = "us-mia"

    # This tells the Linode provider to ignore 
    # node pools with the tag `external`, preventing
    # externally managed node pools from being deleted.
    external_pool_tags = [local.external_pool_tag]

  # Due to certain restrictions in Terraform and LKE, 
  # the cluster must be defined with at least one node pool.
    pool {
        type  = "g6-standard-1"
        count = 1
    }
}
```

You can check detailed doc here: https://registry.terraform.io/providers/linode/linode/latest/docs/resources/lke_node_pool
