### ISSUE TITLE
[Bug]: Unable to use `linode_lke_node_pool` with `linode_lke_cluster`

### ISSUE THREAD

**Issue by lseelenbinder** [linode/terraform-provider-linode#1362]
### Terraform Version

Terraform v1.7.5 on darwin_arm64

### Linode Provider Version

2.17.0

### Effected Terraform Resources

linode_lke_node_pool
linode_lke_cluster

### Expected Behavior

There's a few expected behaviors that aren't supported:

1. You should be able to create a cluster without a `pool` if you have separate `linode_lke_node_pool`s defined.
2. You should be able to create a cluster with a `pool` and with separate `linode_lke_node_pool`s defined and the separate node pools aren't deleted on a new plan.

### Actual Behavior

1. Doesn't work at all (error due to missing `pool`).
2. Creates the nodepool on the first plan and apply. Then tries to delete the separate node pool on the second plan.

### Steps to Reproduce

1. Try to create a cluster and a node pool without a `pool` defined in the cluster resource

For two:

1. Create a cluster with a pool defined.
2. Add a node pool to the cluster with `linode_lke_node_pool`.
3. Apply.
4. Apply a second time -> results in the separate node pool being deleted in the plan.
5. Apply a third time -> results in the pool being recreated.
6. Go back to (4).

**Comment by zliang-akamai** [comment]
Hi @lseelenbinder, thanks for the feedback!

For the first use case, it is a known limitation of the `linode_lke_node_pool` that you can't create a cluster without a pool. 

For the second use case, you will have to specify a tag in `external_pool_tags` to tell the cluster resource which node pool is managed by the node pool resource(s) so it won't delete or update them.

The document is being updated to reflect this limitation in https://github.com/linode/terraform-provider-linode/pull/1363

**Comment by lseelenbinder** [comment]
Hi @zliang-akamai, thanks for the swift feedback! I think the documentation in #1363 definitely closes this for me.
