### ISSUE TITLE
[Bug]: linode_instance_config keep reverting to booted=false

### ISSUE THREAD

**Issue by aborzanovic** [linode/terraform-provider-linode#1397]
### Terraform Version

Terraform v1.4.4 on darwin_arm64

### Linode Provider Version

version = "2.19.0"

### Effected Terraform Resources

linode_instance_config

### Terraform Config Files
```terraform
resource "linode_instance_config" "boot-config" {
  for_each  = local.regions
  label     = "boot_config"
  linode_id = linode_instance.my-instance[each.value].id

  devices {
    sda {
      disk_id = linode_instance_disk.boot-disk[each.value].id
    }
    sdb {
      disk_id = linode_instance_disk.data-disk[each.value].id
    }
  }

  provisioner "remote-exec" {
    inline = local.boot_script

    connection {
      type     = "ssh"
      user     = "private"
      password = "private123456789"
      host     = linode_instance.my-instance[each.value].ip_address
    }
  }

  root_device = "/dev/sda"
  kernel      = "linode/latest-64bit"
  booted      = true
}
```

### Debug Output

  # linode_instance_config.boot-config["us"] will be updated in-place
  ~ resource "linode_instance_config" "boot-config" {
      ~ booted       = false -> true
        id           = "123456789"
        # (7 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

### Expected Behavior

Instance configs, once booted remain booted.

### Actual Behavior

Instance configs revert to booted = false after a while.

### Steps to Reproduce

Create an instance config. Run terraform apply. Wait a month. Run terraform apply again.

I took a quick look at the source code. I'm not confident enough in my go skills to make a pull request. But it seems to me that you're using events filtered for a specific instance in order to determine if the config in question was booted. The problem with that is that events seem to be ephemeral. I glanced at my Linode dashboard and most of my instances don't have a single event whether they've been running for years or months.

I don't know if it's possible to implement this in a more correct way with Linode's API. But if it isn't - even a new attribute which instructs terraform to assume "booted = true" for running instances would solve the issue for me. As things stand right now i'm forced restart these servers very often if i want them in sync with terraform and that's not great in a busy production environment.

**Comment by lgarber-akamai** [comment]
Thank you for the report @aborzanovic!

This is known issue that we are currently tracking internally. Unfortunately we do not have a provider-end workaround as of now due to some API restrictions but you may be able to prevent unexpected reboots using the `ignore_changes` lifecycle rule:

```terraform
resource "linode_instance_config" "boot-config" {
  # ...
  
  booted = true

  lifecycle {
    ignore_changes = ["booted"]
  }
}
```

We'll let you know when we have any updates on this issue 🙂

**Comment by aborzanovic** [comment]
Thanks, I forgot that was an option 🙂
