### ISSUE TITLE
[Feature]: LKE improvements - Basic use cases

### ISSUE THREAD

**Issue by janakg** [linode/terraform-provider-linode#1423]
## Hello Team!
Thanks for maintaining an active Github repo for Linode.
We have started using LKE for deploying some of our compute workloads. It would be great if these features are prioritized as they are basic to Kube clusters

1.  A way to label the nodes created via LKE. e.g.:: prefix can be given as `es-lke-node-`
2. A way to add tags to nodes created via LKE. As there is no other way to differentiate in the Linodes listing. Today we are seeing 100's of nodes without label and tag and it is impossible to make sense out of it in Linodes listing page in console.
3. A way to label the ingress (NodeBalancer) and volumes created during deployment. Or post creation changing the config based on the ids is also fine. I could see one for NodeBalancerConfig, can i use it to update the label alone.
4. There is no way to delete the default pool of a cluster, as we always want to use the NodePool for more control. removeDefaultPool can be an option in cluster creation

Most importantly [1] & [2] - has to work during autoscaling as well.

Please let me know if these are feasible or happy to learn the limitations.

Thanks

https://github.com/pulumi/pulumi-linode/issues/593

**Comment by KartikShrikantHegde** [comment]
Hi @janakg , thank you for reaching out to us. Regarding the enhancements requests above:

#1 i.e Labeling the nodes is planned and in the roadmap for this quarter and rest (#2,#3,#4) are either not planned for now or are being investigated as it involves multiple teams besides LKE. I have created an internal ticket to track these requests.

Meanwhile, our LKE PM is interested to speak with you or your team on above requests and and LKE product in general. If you are interested, would you mind sharing your email here, please? We will send an email from official channel and setup a meeting. Thanks!
