### ISSUE TITLE
[Bug]: Regression in #1260

### ISSUE THREAD

**Issue by aweingarten** [linode/terraform-provider-linode#1491]
### Terraform Version

OpenTofu v1.7.2 on linux_arm64

### Linode Provider Version

linode v2.2.0

### Effected Terraform Resources

"linode_lke_cluster"

### Terraform Config Files

```
resource "linode_lke_cluster" "name" {
    region = "jp-osa"
    k8s_version = "1.30"
    label       = "aweingar-lke-edumacation"

  pool {
    type  = "g6-standard-2"

    autoscaler {
          min = 3
          max = 10
    }
  } 

  control_plane {
    high_availability = true
  }
}
```

### Expected Behavior

I should have gotten a viable plan

### Actual Behavior

```tofu plan
╷
│ Error: Missing required argument
│ 
│   on resources.tf line 6, in resource "linode_lke_cluster" "name":
│    6:   pool {
│ 
│ The argument "count" is required, but no definition was found.
```

### Steps to Reproduce

Creating a new TF resource without a count but with autoscaler should work and was addressed in https://github.com/linode/terraform-provider-linode/pull/1260 and released it in [v.2.14.0](https://github.com/linode/terraform-provider-linode/releases/tag/v2.14.0).  It seems like there may have been a regression somewhere.

**Comment by zliang-akamai** [comment]
Hi @aweingarten, thanks for the bug report! 

I couldn't reproduce the issue locally, and I saw the provider version:

> linode v2.2.0

in you issue description. Can you double check and verify if you are on the latest provider version (`v2.23.0`)? Thank you!

**Comment by aweingarten** [comment]
You are totally right!  My bad! It works as expected.  I was on the wrong version of the provider!
