### ISSUE TITLE
[Feature]: Manage Taints and Labels

### ISSUE THREAD

**Issue by bbetter173** [linode/terraform-provider-linode#1505]
### Description

Now that Linode/Akamai has [added support for managing labels and taints](https://www.linode.com/docs/products/compute/kubernetes/guides/deploy-and-manage-cluster-with-the-linode-api/#add-labels-and-taints-to-your-lke-node-pools) via the API, would it be possible to add support to this provider?

### New or Affected Terraform Resources

linode_lke_cluser

**Comment by ykim-1** [comment]
Hi @bbetter173 , we created some tickets to implement this feature. Will keep you posted if we have any updates on the progress. Thank you for the contribution!
