### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by thoward** [linode/terraform-provider-linode#1618]
The page published at https://registry.terraform.io/providers/linode/linode/latest/docs has a number of broken links to https://www.terraform.io/docs/resources/object_storage_bucket.md and https://www.terraform.io/docs/resources/object_storage_object.md which should be linked to https://registry.terraform.io/providers/linode/linode/latest/docs/resources/object_storage_bucket and https://registry.terraform.io/providers/linode/linode/latest/docs/resources/object_storage_object respectively.

**Comment by thoward** [comment]
Example of markdown source code where link is broken: https://github.com/linode/terraform-provider-linode/blob/dev/docs/index.md?plain=1#L87

I was going to try to edit this and submit a PR, but it's not clear how the docs publishing process works from this repo to Terraform's registry WRT to relative linking. I *think* you could just make the target a relative link to `index.md` e.g. `resources/object_storage_bucket.md` rather than `/docs/resources/object_storage_bucket.md`.

**Comment by yec-akamai** [comment]
Fix in: https://github.com/linode/terraform-provider-linode/pull/1672
