### ISSUE TITLE
Linode Downsize and Upsize Disk Issue

### ISSUE THREAD

**Issue by UnderFenex** [linode/terraform-provider-linode#177]
When I configure a .tf to change the type and disk size in Terraform. I got this issue:

Error: failed to apply instance disk spec: Error resizing disk xxx: size exceeds disk size for Instance yyy

It seems that Terraform is not proceding in order, which is first to resize the disk, then resize the VM in linode. Any solutions?

I'm using the 0.13 terraform core and 1.12.4 linode provider version

tf file:

```
provider "linode" {
  token = "jjjj"
}

resource "linode_instance" "presm11" {
    label             = "label"
    region            = "us-southeast"
    type              = "g6-standard-4"
    config {
        kernel       = "linode/grub2"
        label        = " Disk Profile"
        root_device  = "/dev/sda"
        devices {
            sda {
                disk_label = "Ubuntu 16.04 LTS Disk"
            }
            sdb {
                disk_label = "512 MB Swap Image"
            }
        }
    }
    disk {
        label            = "Ubuntu 16.04 LTS Disk"
        size             = 160000
    }
    disk {
        label            = "512 MB Swap Image"
        size             = 512
    }
}
```

**Comment by Charliekenney23** [comment]
Hello,

This doesn't seem to be a reproducible issue in v1.16.0. When explicitly configuring disks, if the Linode type is upsized, we perform the upsize before we apply the disk configuration. If the Linode type is downsized, we apply the disk configuration before we perform the downsize.

Please feel free to reopen if you're still having issues with this!
