### ISSUE TITLE
Support Versioning & Lifecycle Rules For Object Storage Buckets

### ISSUE THREAD

**Issue by lots0logs** [linode/terraform-provider-linode#185]
### Description
Being able to configure a bucket's versioning and lifecycle rules is extremely important for any serious production use case. See DigitalOcean's Terraform Provider ([Spaces Bucket Resource](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/spaces_bucket#versioning)) for an example of what support could look like.

### New or Affected Resource(s)

* linode_object_storage_bucket

### Potential Terraform Configuration

See: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/spaces_bucket#versioning

**Comment by phillc** [comment]
This has been added as an API feature request on Linode's internal tracker. From there, we'll vet and scope the request for development. You can also submit requests to feedback@linode.com. Thanks!

**Comment by lots0logs** [comment]
@phillc Your API documentation states the following regarding Object Storage endpoints:

> This endpoint is available for convenience. It is recommended that instead you use the more fully-featured S3 API directly.

Are you saying your TF provider can only use your API and not the S3 API directly?

**Comment by phillc** [comment]
Hello,

Our TF provider does currently import the s3 go library, so it is not a matter of it can be done. If someone were to make a pull request that implemented life cycle and versioning rules, we’d definitely consider it. 

I have taken your feedback and added it to our internal tracker. As you mentioned, the end point is currently convenience only. If the API team were to implement this at that end point, we would follow behind with adding the pass through on the terraform resource to the API.

**Comment by lots0logs** [comment]
@phillc I don't understand why you are adding a request to your API tracker when this has really nothing to do with your API. The needed S3 API already exists. Please reopen this issue so that a pull request can be submitted by either myself or another interested developer.

**Comment by Charliekenney23** [comment]
This feature is in the latest release. 😃
