### ISSUE TITLE
Terraform linode Stackscript

### ISSUE THREAD

**Issue by siddharthdex** [linode/terraform-provider-linode#210]
### Terraform Version

Terraform v0.14.5

### Effected Resource(s)

 linode_stackscript

- linode_XXXXXX

### Terraform Configuration Files

Please put your Terraform configuration files in terraform code blocks like the one below.
resource "linode_stackscript" "test" {
  label = "mynode"
  description = "test"
  script = <<EOF
#!/bin/bash
cd /tmp
touch myname.txt
EOF  
images = ["linode/centos7", "linode/centos8"]
rev_note = "1"

}

If your configuration is too complex to be put into code blocks, consider using a Github Gist or a service like Dropbox and share a link to a zip file containing your configuration.

```terraform
# ...
```

### Expected Behavior

Although on server stackscript file present with all the installation steps provided in above program - it simply **not** executing

### Actual Behavior

After provisioning instance the stack script is not getting executed - it show error in weblish as

Welcome to stackscript. stackscript is starting up …
**env: '/root/stackscript': No such file or directory**

### Steps to Reproduce

actual code

terraform {
  required_providers {
    linode = {
      source = "linode/linode"
      version = "1.14.0"
    }
  }
}

provider "linode" {  
  token = ""
}

resource "linode_stackscript" "test" {
  label = "mynode"
  description = "test"
  script = <<EOF
#!/bin/bash
cd /tmp
touch myname.txt
EOF  
images = ["linode/centos7", "linode/centos8"]
rev_note = "1"

}

resource "linode_instance" "mysqldb" {
  image  = "linode/centos8"
  label  = "test-10-centos8"
  region = "ap-south"
  type   = "g6-standard-2"
  #authorized_keys    = ["..."]
  root_pass      = "###"
  stackscript_id = linode_stackscript.test.id

}

**Comment by siddharthdex** [comment]
![image](https://user-images.githubusercontent.com/76903222/106710230-9f700180-661b-11eb-991f-3b598cd95cac.png)

**Comment by phillc** [comment]
Hello. You’ve exposed your api token and need to revoke it immediately.

**Comment by siddharthdex** [comment]
> Hello. You’ve exposed your api token and need to revoke it immediately.

Thank you . Done

**Comment by phillc** [comment]
Hello,

I used this terraform script

```
variable "linode_token" {
  type = string
}
variable "root_pass" {
  type = string
}

terraform {
  required_providers {
    linode = {
      source = "linode/linode"
      version = "1.14.0"
    }
  }
}

provider "linode" {
  token = var.linode_token
}

resource "linode_stackscript" "test" {
  label = "mynode"
  description = "test"
  script = <<EOF
#!/bin/bash
cd /tmp
touch myname.txt
  EOF
  images = ["linode/centos7", "linode/centos8"]
  rev_note = "1"
}

resource "linode_instance" "mysqldb" {
  image = "linode/centos8"
  label = "test-10-centos8"
  region = "ap-south"
  type = "g6-standard-2"
  stackscript_id = linode_stackscript.test.id
  root_pass = var.root_pass
}
```

Then ran

`terraform init` and `terraform apply -var="linode_token=..." -var="root_pass=..." --auto-approve`. I then ssh'd into the linode and was able to successfully see a file with `ls /tmp/myname.txt`.

I see you are on 0.14.5 of terraform, what is your provider version? you can find that with `terraform --version`

**Comment by phillc** [comment]
Hello, if you need further help please feel free to open another issue or contact Linode support.
