### ISSUE TITLE
Apple Silicon darwin_arm64 support

### ISSUE THREAD

**Issue by chakrit** [linode/terraform-provider-linode#223]
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/dnsimple/dnsimple v0.5.1
+ provider registry.terraform.io/linode/linode v1.14.3
```

### Effected Resource(s)
(n/a)

### Terraform Configuration Files
```terraform
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "1.14.3"
    }
    dnsimple = {
      source  = "dnsimple/dnsimple"
      version = "0.5.1"
    }
  }
}
```

### Debug Output
(n/a)

### Panic Output
(n/a)

### Expected Behavior
Init should passes normally.

### Actual Behavior
```
Error: Incompatible provider version

Provider registry.terraform.io/linode/linode v1.14.3 does not have a package
available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

### Steps to Reproduce
1. `terraform init` with linode provider configured

https://github.com/hashicorp/terraform-provider-aws/issues/16948

**Comment by phillc** [comment]
Should be resolved via #225 in https://github.com/linode/terraform-provider-linode/releases/tag/v1.15.0 . Let me know if there are any issues.
