### ISSUE TITLE
terraform refresh command has no effect

### ISSUE THREAD

**Issue by benbro** [linode/terraform-provider-linode#409]
### Terraform Version

Terraform v1.0.3
on linux_amd64

provider registry.terraform.io/linode/linode v1.19.1

### Effected Resource(s)

All resources.

- linode_XXXXXX

### Terraform Configuration Files

```terraform
# ...
```

### Expected Behavior

The [terraform refresh](https://www.terraform.io/docs/cli/commands/refresh.html) command reads the current settings from all managed remote objects and updates the Terraform state to match.
```
terraform refresh
```
or
```
terraform apply -refresh-only
```

### Actual Behavior

The terraform state file doesn't update.

### Steps to Reproduce

1. Create some resources.
2. Delete or clear the local terraform state file.
3. call terraform refresh.
4. Check the terraform state file.

**Comment by LBGarber** [comment]
Hello! 
I wasn't able to reproduce this issue. Is this problem still occurring?
