### ISSUE TITLE
Invalid data source for linode_instances

### ISSUE THREAD

**Issue by campfred** [linode/terraform-provider-linode#430]
### Terraform Version

```
Terraform v1.0.5
on windows_amd64
+ provider registry.terraform.io/linode/linode v1.16.0
```

### Effected Resource(s)

- linode_instances

### Terraform Configuration Files

```terraform
# Based on How to Deploy a Linode Kubernetes Engine Cluster Using Terraform
# https://www.linode.com/docs/guides/how-to-deploy-an-lke-cluster-using-terraform/

terraform {
    required_providers {
        linode = {
            source = "linode/linode"
            version = "1.16.0"
        }
    }
}
# Use the Linode Provider
provider "linode" {
    token = var.token
}

resource "linode_lke_cluster" "TestCluster" {
    k8s_version = var.k8s_version
    label = var.label
    region = var.region
    tags = var.tags

    dynamic "pool" {
        for_each = var.pools
        content {
            type	= pool.value["type"]
            count = pool.value["count"]
        }
    }
}

data "linode_instances" "TestCluster" {
    filter {
        name = "id"
        values = [linode_lke_cluster.TestCluster.id]
    }
}

resource "linode_volume" "TestCluster" {
    label = linode_lke_cluster.TestCluster.label
    region = linode_lke_cluster.TestCluster.region
    linode_id = linode_instances.id
    size = var.volume_size
}

output "kubeconfig" {
    value = linode_lke_cluster.TestCluster.kubeconfig
    sensitive = true
}

output "api_endpoints" {
    value = linode_lke_cluster.TestCluster.api_endpoints
}

output "status" {
    value = linode_lke_cluster.TestCluster.status
}

output "linode_id" {
    value = linode_instances.id
}

output "cluster_id" {
    value = linode_lke_cluster.TestCluster.id
}

output "volume_id" {
    value = linode_volume.TestCluster.id
}

output "pool" {
    value = linode_lke_cluster.TestCluster.pool
}
```

### Debug Output

https://gist.github.com/campfred/29e5463a19eafb30b49da12ef40e3192

### Expected Behavior

Based on [the provider documentation for the instance datasource](https://registry.terraform.io/providers/linode/linode/latest/docs/data-sources/instances), it should have obtained Linode instance(s) infos that I would have been able to use afterward to provision other things.

### Actual Behavior

An error is thrown that the data source does not exist.

```
╷
│ Error: Invalid data source
│
│   on main.tf line 36, in data "linode_instances" "RaccPacc":
│   36: data "linode_instances" "RaccPacc" {
│
│ The provider linode/linode does not support data source "linode_instances".
╵
```

### Steps to Reproduce

1. Setup an LKE Cluster (either through the Terraform script or through Linode's control panel)
2. Try to obtain the instance's attributes that's hosting the LKE Cluster through a Terraform script
   > I was doing this to obtain the Linode ID that's hosting the cluster to attach a volume storage created at the end of my configurations file before the output exports.
3. Ask Terraform to plan the changes with a `terraform plan`
   > In my case, since I'm using variables, I have a `variables.tf` file defining them like in my Configuration file and a `terraform.tfvars` filling out the required ones.

**Comment by LBGarber** [comment]
Hey there! 
The `linode_instances` data source was added in provider version `v1.17.0`.  Could you try upgrading to a newer version of the provider?

**Comment by campfred** [comment]
> Hey there!
> The `linode_instances` data source was added in provider version `v1.17.0`. Could you try upgrading to a newer version of the provider?

Indeed! It looks like Linode's own documentation wasn't completely up to date as they're still giving examples with v1.16. My apologies!
Knowing that, I will look with them for an update on their end. Thank you very much!
