### ISSUE TITLE
IPv6 example in linode_firewall docs is confusing

### ISSUE THREAD

**Issue by benbro** [linode/terraform-provider-linode#431]
### Description

IPv6 example in the [linode_firewall docs](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/firewall) is:
```tf
ipv6     = ["ff00::/8"]
```
To accept all IPv6 addresses It should be:
```tf
ipv6     = ["::/0"]
```

### New or Affected Resource(s)

linode_firewall

### Potential Terraform Configuration

```tf
ipv6     = ["::/0"]
```

**Comment by LBGarber** [comment]
Hello! 
Thanks for the suggestion! I put up a quick PR to improve this in our documentation. Let us know if you run into anything else!
