### ISSUE TITLE
Boot config missing : Complex instance not creating boot config

### ISSUE THREAD

**Issue by arpanrec** [linode/terraform-provider-linode#454]
### Terraform Version

Terraform v1.0.5 on linux_amd64

### Terraform Configuration Files

resource "linode_instance" "vault_server" {
  label      = "sa-m1-vault.hld"
  region     = "ap-west"
  type       = "g6-nanode-1"
  private_ip = true
  disk {
    label           = "boot"
    size            = 25088
    image           = "linode/ubuntu20.04"
    authorized_keys = ..
  }
  config {
    label  = "boot_config"
    kernel = "linode/grub2"
    devices {
      sda {
        disk_label = "boot"
      }
      sdb {
        volume_id = linode_volume.ss_storage.id
      }
    }
    root_device = "/dev/sda"
  }
  boot_config_label = "boot_config"
}

### Debug Output

Error: Error waiting for Linode instance xxxxxx disk: [002] Get "https://api.linode.com/v4/account/events?page=1
Error: Error waiting for Linode instance xxxxxx disk: [002] Get "https://api.linode.com/v4/account/events?page=1": context deadline exceeded

![Screenshot from 2021-08-31 14-59-09](https://user-images.githubusercontent.com/26441134/131478820-00aa44a4-6b55-4078-9ec6-77995746299c.png)

**Comment by LBGarber** [comment]
Hello, thanks for the report!

I haven't been able to reproduce this issue on my end. Typically these `context deadline exceeded` errors imply an intermittent issue communicating with the Linode API or an event taking much longer than expected. Typically these issues can be resolved by re-running `terraform apply`.

Let me know if you're still running into this and I'll investigate it further!

**Comment by arpanrec** [comment]
@LBGarber exactly, https://api.linode.com/v4/account/events?page=1 api sometimes not returning the latest event, and rerunning the terraform fixs these, but instate of checking the event log, is it possible to check if the actual resource is provisioned?

**Comment by LBGarber** [comment]
Directly checking for a resource to be provisioned is not currently possible without a change to our underlying polling logic. It's possible this issue was introduced by [this change](https://github.com/linode/linodego/commit/518ee060e253c483e3c9cfe6817e7de3b9f736b7#diff-904bd3d16d52b4d495ecbb5db8ac1d4db55ce10360f91987e9dece5dfa2790c0R268) (linodego v0.31.0, terraform-provider-linode v1.20.0). 

I'm curious to know if this issue occurs for you with provider versions prior to v1.20.0.

**Comment by arpanrec** [comment]
Found the issue, it's a bug.
Steps to reproduce:
Step 1) Start your terraform apply.
Step 2) When few of your resources are created then, Visit Console dashboard https://cloud.linode.com
Step 3) You can see some resources changed notification.
![Screenshot from 2021-08-31 21-23-01](https://user-images.githubusercontent.com/26441134/131536024-fdb76473-584e-4fe1-bd29-4210f696d971.png)
Step 4) Click on it to check the notifications.
![Screenshot from 2021-08-31 21-23-43](https://user-images.githubusercontent.com/26441134/131536160-adc84ea0-fcf4-40e0-9027-eda688dc4707.png)
Step 5) You will see unread notification counter is not showing now unread notification anymore.
Step 6) You will see your terraform playbook is stuck.

## Root cause
when terraform requests for a resource change it waits for https://api.linode.com/v4/account/events?page=1 this API to show the actual change request is completed or not. something like 
{
            "id": xxxxxxx,
            "created": "2021-08-31T15:52:07",
            "seen": false,
            "read": false,
            "percent_complete": 100,
            "time_remaining": 0,
            "rate": null,
            "duration": 16.0,
            "action": "linode_shutdown",
            "username": "xxxxxxx",
            "entity": {
                "label": "sa-m1-vault.hld",
                "id": xxxxxxx,
                "type": "linode",
                "url": "/v4/linode/instances/xxxxxx"
            },
            "status": "finished",
    
        }

But when I am clearing the notification counter on "Step 4" it's injecting below profile_update event.
{
            "id": xxxxxx,
            "created": "2021-08-31T15:53:52",
            "seen": false,
            "read": false,
            "percent_complete": null,
            "time_remaining": null,
            "rate": null,
            "duration": null,
            "action": "profile_update",
            "username": "xxxxxxx",
            "entity": {
                "label": null,
                "id": null,
                "type": "profile",
                "url": "/v4/profile"
            },
            "status": "notification",
            "secondary_entity": null,
            "message": ""
        }

Now when terraform is checking it's getting this profile update as the latest event. and never got the actual resource event, because it's now second on the list.

Possible Solution:
Add a condition if "action": "profile_update", then skip it and go to next event.

**Comment by LBGarber** [comment]
Thanks for the detailed report! I'll look into possible solutions for this.
