### ISSUE TITLE
Error when importing linode_domain_record to the state

### ISSUE THREAD

**Issue by benbro** [linode/terraform-provider-linode#467]
### Terraform Version

Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/linode/linode v1.20.2

### Effected Resource(s)

- linode_domain_record

### Terraform Configuration Files

```terraform
resource "linode_domain" "test" {
  type = "master"
  domain = "example.com"
  soa_email = "contact@example.com"
  ttl_sec = 300
}

resource "linode_domain_record" "test" {
    domain_id = linode_domain.test.id
    name = "@"
    record_type = "A"
    target = "11.22.333.444"
}
```

### Expected Behavior

linode_domain_record should be imported

### Actual Behavior
```
linode_domain_record.test: Importing from ID "123456"...

Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```

### Steps to Reproduce
```

1. Create linode_domain with terrafrom apply
2. Create A domain record with empty hostname manually (outside of terraform in the cloud console)
3. Try to import the existing domain record to the terraform state:
terraform import linode_domain_record.test 123456
```

**Comment by LBGarber** [comment]
Hello!

It looks like this error is thrown when only one argument is passed into `terraform import linode_domain_record.___`. It looks like our provider didn't properly report these errors, so I put up a quick PR to improve this logic.

Let us know if you find anything else! :+1:
