### ISSUE TITLE
linode_domain_record.ttl_sec omits options under 300 seconds, despite them being available in the UI

### ISSUE THREAD

**Issue by finnbear** [linode/terraform-provider-linode#484]
### Terraform Version

```console
Terraform v1.0.1
on linux_amd64
```

### Effected Resource(s)

linode_domain_record

### Terraform Configuration Files

```terraform
resource "linode_domain" "main" {
  type = "master"
  domain = var.domain
  soa_email = ".................."
  tags = [var.name]
}

resource "linode_domain_record" "home_ipv4" {
  count = var.servers
  domain_id = linode_domain.main.id
  name = ""
  record_type = "A"
  target = element(linode_instance.servers.*.ip_address, count.index)
  ttl_sec = 30 # the issue
}
```

### Expected Behavior

My record is configured to have 30 second ttl, as in:
![image](https://user-images.githubusercontent.com/20015102/133648886-5ec726ca-a1f4-4e9c-a36a-08e9cfc7bd73.png)

This is consistent with the options presented in the UI:
![image](https://user-images.githubusercontent.com/20015102/133649199-c39f8b27-ea2b-46bd-a564-0eae95ce5235.png)

My hope is that this lower ttl will increase the chances of my Round-Robin DNS loadbalancing strategy working.

### Actual Behavior

My record is configured to have 300 second ttl, as in:
![image](https://user-images.githubusercontent.com/20015102/133648937-3419a003-c562-4f7b-ba4b-24c3a80db63d.png)

This is consistent with the options presented in the docs:
![image](https://user-images.githubusercontent.com/20015102/133648836-a0cf2055-4f15-4544-bc86-5a93a97e4cc1.png)

### Steps to Reproduce

1. Create a `linode_domain`
2. Create a `linode_domain_record` with `ttl = 30`
3. Observe ttl is rounded up to 300

### Note

I believe the bug is that the array here is missing several valid values, namely 30 and 120: https://github.com/linode/terraform-provider-linode/blob/56b85508d9284709a69c41e7f439fe071d61bcfb/linode/helper/domain.go#L11

But I also realize this may not be a bug, and you have simply changed your mind about offering low TTLs. Still, I would question the logic of offering them in the UI but not via terraform.

**Comment by LBGarber** [comment]
Hello! Thanks for the detailed issue report!

It looks like these values went under our radar when creating this resource. Normally we would defer this validation logic to the API, but the API rounds TTLs to the nearest valid TTL which could potentially introduce an inconsistent state. I'll put up a PR to add these additional TTLs to our client-side validation.

Let me know if you have any more issues!
