### ISSUE TITLE
[Bug]: When using VLANs, public interface must be defined first

### ISSUE THREAD

**Issue by inflatador** [linode/terraform-provider-linode#508]
### Terraform Version

Terraform v1.0.4 on darwin_amd64

### Linode Provider Version

linode v1.22.0

### Effected Terraform Resources

linode_instance

### Terraform Config Files

  ```
config {
    label = "linode_boot_config"
    kernel = "linode/grub2"
    interface {
      purpose = "vlan"
      label = "my_net"
        }
     interface {
          purpose = "public"
      // public interfaces cannot have a label
        }
    devices {
      sda {
        disk_label = "bootme"
        }
      }
    root_device = "sda"
        }
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Linode instances come up with network connectivity, regardless of the order of interfaces as defined in the terraform file.

### Actual Behavior

Note: this was tested via Linode's Atlanta DC.

Linode instances come up with no network connectivity. Interface 'eth0' (presumably the VLAN interface) has no IP configuration, and 'eth1' (presumably the public interface) do not work.

Via the lish console, I removed eth1's public IPv4 address and the default route, then added the IP and route pointing to eth0, but that didn't work either.

### Steps to Reproduce

Create a VLAN in the Atlanta DC.
Add 2 interface blocks to your config section, with the VLAN specified first. Specifically, place this within the linode_instance block within your terraform file.

**Comment by LBGarber** [comment]
Hello! Thanks for the report!
This behavior is intended but was previously not well documented. This has been added to our documentation and can be viewed here:
https://www.linode.com/docs/products/networking/vlans/

Let me know if you run into any more issues! :smile:
