### ISSUE TITLE
renaming a disk attempts to delete the disk instead of updating in place

### ISSUE THREAD

**Issue by iamcodemaker** [linode/terraform-provider-linode#524]
### Terraform Version
terraform 1.0.4

### Affected Resource(s)

- linode\_instance

### Terraform Configuration Files
```hcl
resource "linode_instance" "my-server" {
  label           = "my-server"
  region          = "us-west"

  type              = "g6-standard-2"
  boot_config_label = "standard"

  config {
    kernel       = "linode/latest-64bit"
    label        = "standard"
    memory_limit = 0
    root_device  = "/dev/sda"
    run_level    = "default"
    virt_mode    = "paravirt"

    devices {
      sda {
        disk_label = "main"
      }

      sdb {
        disk_label = "swap"
      }
    }

    helpers {
      devtmpfs_automount = true
      distro             = true
      modules_dep        = true
      network            = false
      updatedb_disabled  = true
    }
  }

  disk {
    filesystem = "swap"
    label      = "swap"
    size       = 256
  }
  disk {
    filesystem = "ext4"
    label      = "main"
    size       = 10128
  }
}
```

### Expected Behavior
The disk in linode is named "256mb swap", I would expect the disk to be renamed to "swap". This is what `terraform plan` says will happen.

### Actual Behavior
Terraform attempts to delete the disk and fails (probably because it is in use). I assume it was going to delete, then re-create the disk.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a new instance similar to the one above.
2. Attempt to rename the swap disk.

### Important Factoids
I'm not sure if the above config is 100% valid (I re-created it from one of my more complex configs). You get the idea though. Renaming the disk manually in linode and then changing the name in the `.tf` file works as expected.

**Comment by LBGarber** [comment]
This bug has been resolved in the new [`linode_instance_disk` resource](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance_disk) introduced in provider version `v1.29.1`.
