### ISSUE TITLE
[Bug]: adding a disk with read_only or filesystem specified causes the whole instances to be re-created

### ISSUE THREAD

**Issue by iamcodemaker** [linode/terraform-provider-linode#525]
### Terraform Version

1.0.4

### Linode Provider Version

version = "1.20.2"

### Effected Terraform Resources

linode_instance

### Terraform Config Files

```hcl
resource "linode_instance" "my-server" {
  label           = "my-server"
  region          = "us-west"

  type              = "g6-standard-2"
  boot_config_label = "standard"

  config {
    kernel       = "linode/latest-64bit"
    label        = "standard"
    memory_limit = 0
    root_device  = "/dev/sda"
    run_level    = "default"
    virt_mode    = "paravirt"

    devices {
      sda {
        disk_label = "main"
      }

      sdb {
        disk_label = "swap"
      }
    }

    helpers {
      devtmpfs_automount = true
      distro             = true
      modules_dep        = true
      network            = false
      updatedb_disabled  = true
    }
  }

  disk {
    filesystem = "swap"
    label      = "swap"
    size       = 256
  }
  disk {
    filesystem = "ext4"
    label      = "main"
    size       = 10128
  }
}
```

### Expected Behavior

A new disk should be added.

### Actual Behavior

`terraform plan` reports the entire instance will be deleted and recreated because of the `filesystem` and `read_only` setting for the new disk. Removing those attributes allows a new disk to be created with the `ext4` filesystem as expected.

### Steps to Reproduce

1. Create linode instance similar to the one above.
2. Add a disk in the tf resource with the `filesystem` parameter specified.

**Comment by LBGarber** [comment]
Hey there! @iamcodemaker 

This bug has been resolved in the new [`linode_instance_disk` resource](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance_disk) introduced in provider version `v1.29.1`. 

Let me know if you run into anything else :slightly_smiling_face:
