### ISSUE TITLE
[Feature]: attach linode to cloud firewalls without having a monolithic plan

### ISSUE THREAD

**Issue by chrisdlangton** [linode/terraform-provider-linode#544]
### Description

Currently you must have one monolithic terraform plan when you use `linode_firewall`

The *only* method to attach a linode to he firewall is to have all of the `linode_instance` definitions in the same plan as the `linode_firewall` definition.

This is not a good pattern when you split `linode_instance` into each repository they correspond to.

There needs to be a way to attch the `linode_instance` without having a monolith repository and plan built around the `linode_firewall`

### New or Affected Terraform Resources

related;
- linode_firewall
- linode_instance

### Potential Terraform Configuration

suggested new, similar to `linode_nodebalancer_node`:
```
resource "linode_firewall_node" "my_firewall_attachment" {
    firewall_id = <int>
    linode = <int>
}
```

See: https://www.linode.com/docs/api/networking/#firewall-create

The tricky part will be the *availability* concerns. i.e. management of the `linode_firewall`.`linodes` resource in one plan that defines a firewall, and other external plans that have a `linode_firewall_node` adding a single linode each not wiping out legitimate attached linodes, or being purged when the `linode_firewall` plan runs next.

One solution is this API call:
```sh
LINODE_ID=$(curl -s -H "Authorization: Bearer ${TF_VAR_linode_token}" https://api.linode.com/v4/linode/instances | jq -r '.data[] | select(.label=="MY_COOL_LABEL") | .id')
curl -s -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${TF_VAR_linode_token}" \
  -X POST -d '{"type": "linode", "id": ${LINODE_ID}}' \
  https://api.linode.com/v4/networking/firewalls/${LINODE_FIREWALL_ID}/devices
```

**Comment by LBGarber** [comment]
Thanks for the great suggestion!

This feature has been added and will be available in the next release.

Let us know if you have any other issues or suggestions. 🙂
