### ISSUE TITLE
[Bug]: lifecycle_rule doesn't delete objects

### ISSUE THREAD

**Issue by benbro** [linode/terraform-provider-linode#578]
### Terraform Version

Terraform v1.1.2 on linux_amd64

### Linode Provider Version

version = "1.25.0"

### Effected Terraform Resources

linode_object_storage_bucket

### Terraform Config Files

```terraform
resource "linode_object_storage_bucket" "mybucket" {
  access_key = linode_object_storage_key.project.access_key
  secret_key = linode_object_storage_key.project.secret_key

  cluster = data.linode_object_storage_cluster.project.id
  
  label = "mybucket"
  
  lifecycle_rule {
    enabled = true
    expiration {
      days = "10"
    }
  }
}
```

### Expected Behavior

Objects should get deleted automatically after 10 days.

### Actual Behavior

Objects are not deleted.

### Steps to Reproduce

Apply the resource and wait 10 days for the object to get deleted.

**Comment by LBGarber** [comment]
Hey there! 🙂 

Just to narrow down the issue a bit more, could you verify the lifecycle configuration has been properly applied to your cluster?

This can be done using the following `s3cmd` commands:
```bash
s3cmd getlifecycle s3://mybucket
```
```bash
s3cmd info s3://mybucket | grep Expiration
```

**Comment by benbro** [comment]
I actually used a different number of expiration days but my terraform settings matches the output of s3cmd

```bash
s3cmd getlifecycle s3://mybucket
```
```xml
<?xml version="1.0" ?>
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<Rule>
		<ID>rule-id</ID>
		<Prefix/>
		<Status>Enabled</Status>
		<Expiration>
			<Days>10</Days>
		</Expiration>
	</Rule>
</LifecycleConfiguration>
```
```bash
s3cmd info s3://mybucket | grep Expiration
   Expiration Rule: all objects in this bucket will expire in '10' day(s) after creation
```

**Comment by LBGarber** [comment]
@benbro I did a bit of testing and was able to reproduce this issue on Frankfurt (`eu-central-1`). Could you clarify which cluster/region this issue was occurring for you in?

**Comment by benbro** [comment]
Yes, I have this on eu-central-1. Is there ETA for a fix?

**Comment by LBGarber** [comment]
> Yes, I have this on eu-central-1. Is there ETA for a fix?

Thanks for the info! I'll forward this to the appropriate team and keep you updated.
