### ISSUE TITLE
[Feature]: Ability to update firewall rules

### ISSUE THREAD

**Issue by mox1** [linode/terraform-provider-linode#625]
### Description

Currently (as far as I can tell) all of the rules for a firewall must be added to the creation request. IE there is no way to create an additional firewall rule and attach it to an existing firewall policy.

I believe this is available with the API via:  https://www.linode.com/docs/api/networking/#firewall-rules-update 

### New or Affected Terraform Resources

linode_firewall_rule

### Potential Terraform Configuration

```
resource "linode_firewall_rule" "example1"{
   #existing firewall id
    id = '123456'
    inbound {
        label     = "Allow_Inbound_DNS"
        action    = "ACCEPT"
        protocol  = "UDP"
        ports     = "53"
        ipv4      = ["0.0.0.0/0"]

    }
}
```

**Comment by LBGarber** [comment]
Hi there, thanks for the suggestion!

If you don't mind me asking, could you explain your use case for this feature? We might be able to point you in the right direction while we investigate the viability of implementing this.

**Comment by mox1** [comment]
We are using Linode firewall to do network based whitelisting. By default we allow nothing through the firewall, and dynamically add some IP addresses / ports we want. 

We have a Terraform script that can optionally add / install DNS services onto a new Linode server. As part of that I wanted to add a rule to the firewall that was just created to allow incoming DNS. Basically we have a separate "null_resources" block that optionally does this. A firewall was created in the main resource, this resource just executes a few shell commands. It would be nice to add an additional inbound firewall rule to the firewall that was just created. 

More generically, the Linode Firewall workflow allows adding and removing of rules AFTER the creation of the firewall itself. I don't see a way to replicate this workflow within Terraform, All firewall rules must be defined at firewall creation.

**Comment by LBGarber** [comment]
Thanks for the quick response!

As you stated, the Terraform provider does not directly offer a way to update firewall rules independently from the `linode_firewall` resource. If you aren't using them already, you may be able to achieve something similar using [dynamic blocks](https://www.terraform.io/language/expressions/dynamic-blocks).

For example:
```hcl
variable "whitelisted_ports" {
  # Example IP ports to create rules for
  default = [80, 443]
  type=list(number)
}

resource "linode_firewall" "my-firewall" {
  label = "my-firewall"

  inbound_policy = "DROP"
  outbound_policy = "ACCEPT"

  # Create an inbound rule for every port in var.whitelisted_ports
  dynamic "inbound" {
    for_each = var.whitelisted_ports

    content {
      label = "allow-port-${inbound.value}"
      action = "ACCEPT"
      protocol = "TCP"
      ports = "80"
      ipv4 = ["192.168.0.1/32", "192.168.0.2/32", "192.168.0.3/32"]
    }
  }

  linodes = []
}
```

I recognize that this structure isn't ideal for every use case so I'll continue discussing this with my team and get back to you once we've come to a decision :+1:

**Comment by nicksterious** [comment]
+1 for this feature
