### ISSUE TITLE
[Bug]: Terraform linode_lke_cluster times out too soon, after 30 secs, and leaves orphaned nodes

### ISSUE THREAD

**Issue by blue928** [linode/terraform-provider-linode#628]
### Terraform Version

1.1.9

### Linode Provider Version

1.23.0

### Effected Terraform Resources

linode_lke_cluster
### Terraform Config Files

The following code follows this Linode tutorial https://www.linode.com/docs/guides/how-to-deploy-an-lke-cluster-using-terraform/
```
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
    helm = {
      source = "hashicorp/helm"
    }
    kubectl = {
      source = "gavinbunney/kubectl"
      #version = ">= 1.7.0"
    }
  }
}

# Configure the Linode Provider
provider "linode" {
  # token = "..."
  token = var.linode_token
}

resource "linode_lke_cluster" "peggyburkosky_prod" {
    label       = var.label
    k8s_version = var.k8s_version
    region      = var.region
    tags        = var.tags

    pool {
        type  = var.pool_type
        count = var.pool_count
    }
}

variable "linode_token" {
  default = ""
  sensitive = true
}

variable "label" {
  default = "peggyburkosky"
  type = string
}

variable "k8s_version" {
  default = "1.23"
  type = string 
}

variable "region" {
  default = "us-east"
  type = string
}

variable "tags" {
  default = ["prod"]
  type = list
}

variable "pool_type" {
  default = "g6-standard-1"
  type = string
}

variable "pool_count" {
  default = 1
  type = number
}

### Debug Output

_No response_

### Panic Output

_No response_

### Expected Behavior

The expected behavior is that the resource `linode_lke_cluster` will wait until the resource is configured before terminating. As well, expected behavior is that there should be a resource argument to specify waiting or at least stipulating a reasonable time period for cluster creation to complete. (30 secs is way too short.) Also, I'm not sure what the "label" argument is supposed to do, but it does not name the orphaned resource correctly. Instead, it's a random uuid generated by whereas the resource generated should be the label name (or we should be able to specify it regardless).

### Actual Behavior

The following terminal output walks one through exactly what is happening (see below). In a nutshell, terraform terminates after 30 seconds throwing an error that the tcp connection has been reset by peer. The problem is that this creates abandoned resources that are not under the control of Terraform. Sure if there are one or two we could go in and simply delete them manually. But, of course that defeats the purpose of Terraform the bigger issue is that we have no clue what resource was legitimately created and which ones need to be manually managed in large node pools

```
Terraform will perform the following actions:

  # linode_lke_cluster.peggyburkosky_prod will be created
  + resource "linode_lke_cluster" "peggyburkosky_prod" {
      + api_endpoints = (known after apply)
      + dashboard_url = (known after apply)
      + id            = (known after apply)
      + k8s_version   = "1.23"
      + kubeconfig    = (sensitive value)
      + label         = "peggyburkosky"
      + region        = "us-east"
      + status        = (known after apply)
      + tags          = [
          + "prod",
        ]

      + control_plane {
          + high_availability = (known after apply)
        }

      + pool {
          + count = 1
          + id    = (known after apply)
          + nodes = (known after apply)
          + type  = "g6-standard-1"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + api_endpoints = (known after apply)
  + id            = (known after apply)
  + kubeconfig    = (sensitive value)
  + pool          = [
      + {
          + autoscaler = []
          + count      = 1
          + id         = (known after apply)
          + nodes      = (known after apply)
          + type       = "g6-standard-1"
        },
    ]
  + status        = (known after apply)

──────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take
exactly these actions if you run "terraform apply" now.

Terraform used the selected providers to generate the following execution plan. Resource actions
are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # linode_lke_cluster.peggyburkosky_prod will be created
  + resource "linode_lke_cluster" "peggyburkosky_prod" {
      + api_endpoints = (known after apply)
      + dashboard_url = (known after apply)
      + id            = (known after apply)
      + k8s_version   = "1.23"
      + kubeconfig    = (sensitive value)
      + label         = "peggyburkosky"
      + region        = "us-east"
      + status        = (known after apply)
      + tags          = [
          + "prod",
        ]

      + control_plane {
          + high_availability = (known after apply)
        }

      + pool {
          + count = 1
          + id    = (known after apply)
          + nodes = (known after apply)
          + type  = "g6-standard-1"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + api_endpoints = (known after apply)
  + id            = (known after apply)
  + kubeconfig    = (sensitive value)
  + pool          = [
      + {
          + autoscaler = []
          + count      = 1
          + id         = (known after apply)
          + nodes      = (known after apply)
          + type       = "g6-standard-1"
        },
    ]
  + status        = (known after apply)
linode_lke_cluster.peggyburkosky_prod: Creating...
linode_lke_cluster.peggyburkosky_prod: Still creating... [10s elapsed]
linode_lke_cluster.peggyburkosky_prod: Still creating... [20s elapsed]
linode_lke_cluster.peggyburkosky_prod: Still creating... [30s elapsed]
╷
│ Error: failed to create LKE cluster: [002] Post "https://api.linode.com/v4/lke/clusters": read tcp [2603:6081:2a40:3915:1c29:3912:a9fd:a11f]:51222->[2600:3c00::23]:443: read: connection reset by peer
│ 
│   with linode_lke_cluster.peggyburkosky_prod,
│   on linode_lke_cluster.tf line 1, in resource "linode_lke_cluster" "peggyburkosky_prod":
│    1: resource "linode_lke_cluster" "peggyburkosky_prod" {
│ 
```

### Steps to Reproduce

See the "Actual Behavior" field, but use the code from the tutorial or my script above and type terraform init, validate, plan, apply, etc

**Comment by blue928** [comment]
Working with the ticketing team we've discovered that this is an IPv6 issue.

I'm in an environment where we have to use IPv6 for work. I've run the tests several times behind IPv6 from two different service providers (ATT and Spectrum). This fails every single time at 30 seconds. If I use IPv4 it works every single time. Spectrum will auto switch from IPv6 to IPv4 if there is an issue with 6, but that forwarding also causes it to fail at 30 seconds. 

What's the issue here? If IPv6 works fine for AWS, Azure, and GC, does the logic in the linode resource or LKE that does not handle IPv6 connections properly? Is there something in LKE I need to configure to work while I'm behind an IPv6 address? I won't always have IPv4 access.

**Comment by lgarber-akamai** [comment]
Hi there @blue928

Just following up to see if there have been any developments around this situation.
