### ISSUE TITLE
[Feature]: linode_volume Cloning

### ISSUE THREAD

**Issue by lseelenbinder** [linode/terraform-provider-linode#629]
### Description

It would be great to use an existing volume to create a new one.

### New or Affected Terraform Resources

linode_volume

### Potential Terraform Configuration
```
linode_volume {
  region = "us-east"
  label = "clone-of-vol-x"
  source_volume_id = "vol-x-id"
}
```

**Comment by LBGarber** [comment]
Thanks for the request!
I've added this to our internal tracker and I'll let you know when I have any updates 🙂
