### ISSUE TITLE
[Bug]: plugin crashed

### ISSUE THREAD

**Issue by benbro** [linode/terraform-provider-linode#630]
### Terraform Version

Terraform v1.1.9 on linux_amd64

### Linode Provider Version

version = "1.2.7.0"

### Effected Terraform Resources

linode_object_storage_bucket

### Panic Output

Stack trace from the terraform-provider-linode_v1.27.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference

goroutine 136 [running]:

Error: The terraform-provider-linode_v1.27.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

No crash

### Actual Behavior

Crash

### Steps to Reproduce

Try to create linode_object_storage_bucket with 1.2.7.0.

**Comment by LBGarber** [comment]
Hey there! 
This seems to be an issue that was introduced in a `1.27.0` change. I'll see if I can get this fixed today.

**Comment by LBGarber** [comment]
@benbro This issue has been resolved in `v1.27.1`. Let me know if you run into any more issues :slightly_smiling_face:

**Comment by benbro** [comment]
Thank you for the quick fix.

When the plugin crashed the state in terraform wasn't synced with the resources created on Linode.
The plan created a new instance on Linode and terraform tried to re-create it when run again.

Another issue is that using the ```terraform destroy``` command when the plan has several resources (instances, buckets, firewalls...) is very slow and often fail. I'll open a separate issue.
