### ISSUE TITLE
[Feature]: linode_lke_cluster node pool should have an initial_count value instead of count 

### ISSUE THREAD

**Issue by cylarez** [linode/terraform-provider-linode#639]
### Description

When using LKE with the autoscaler option, the count of nodes will obviously change and running terraform is currently destroying your nodes because it is applying the initial "count" value. 
I think we need some sort of "initial_count" config that should be used the first time and ignored when using the autoscaler. So it won't destroyed the nodes that were created by the node pool autoscaling feature. (similar to what google is doing with their terraform module for GKE)

### New or Affected Terraform Resources

linode_lke_cluster

**Comment by LBGarber** [comment]
Hey there! I'll bring this up with my team and see if we can find a clean way to implement this.

As a workaround to prevent autoscaler nodes from being destroyed, you might be able to use [ignore changes](https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes) in a `lifecycle` block.

For example:
```hcl
resource "linode_lke_cluster" "my-cluster" {
  label       = "my-cluster"
  k8s_version = "1.23"
  region      = "us-southeast"

  pool {
    type  = "g6-standard-2"
    count = 3

    autoscaler {
      min = 3
      max = 10
    }
  }

  lifecycle {
    ignore_changes = [
      # We should ignore changes on the `count` field for all autoscaler pools
      pool.0.count
    ]
  }
}
```
