### ISSUE TITLE
[Bug]: linode_firewall_device entity_id does not accept a list?

### ISSUE THREAD

**Issue by iehrenwald** [linode/terraform-provider-linode#716]
### Terraform Version

1.2.9

### Linode Provider Version

1.29.4

### Effected Terraform Resources

linode_firewall_device

### Terraform Config Files

resource "linode_firewall_device" "my_device" {
  firewall_id = linode_firewall.my_firewall.id
  entity_id = [ linode_instance.my_instance.id, linode_instance.my_other_instance.id ]
}

resource "linode_firewall" "my_firewall" {
  label = "my_firewall"

  inbound {
    label    = "http"
    action = "ACCEPT"
    protocol  = "TCP"
    ports     = "80"
    ipv4 = ["0.0.0.0/0"]
    ipv6 = ["::/0"]
  }

  inbound_policy = "DROP"
  outbound_policy = "ACCEPT"
}

resource "linode_instance" "my_instance" {
  label      = "my_instance"
  region     = "us-southeast"
  type       = "g6-standard-1"
}

resource "linode_instance" "my_other_instance" {
  label      = "my_other_instance"
  region     = "us-southeast"
  type       = "g6-standard-1"
}

### Debug Output

│ Error: Incorrect attribute value type
│
│   on fwd.tf line 3, in resource "linode_firewall_device" "my_device":
│    3:   entity_id = [ linode_instance.my_instance.id, linode_instance.my_other_instance.id ]
│     ├────────────────
│     │ linode_instance.my_instance.id will be known only after apply
│     │ linode_instance.my_other_instance.id will be known only after apply
│
│ Inappropriate value for attribute "entity_id": number required.

### Expected Behavior

The linodes specified by ID in the list passed to entity_id within the linode_firewall_device will be attached.

### Actual Behavior

Terraform/Linode provider kicks back with incorrect attribute value type, when it should in reality be able to take a list.  I am unclear on when/whether to actually use linode_firewall_device vs creating a resource of type linode_firewall and using the linodes attribute which does accept a list.

### Steps to Reproduce

Copy/paste the example code from https://registry.terraform.io/providers/linode/linode/latest/docs/resources/firewall_device into a new working directory, add provider details as needed.  Run terraform init && terraform plan.  Then add another linode_instance resource definition, and run terraform plan again.

**Comment by lgarber-akamai** [comment]
Thanks for the report!

At the moment, the `linode_firewall_device` resource represents a 1:1 relationship between an entity and a firewall. This mirrors the [equivalent API resource](https://www.linode.com/docs/api/networking/#firewall-device-create). Because of this, multiple firewall devices should be created for each entity/firewall assignment.

We realize this isn't the best UX and we'll be looking into ways to improve this in the future.

Let me know if you run into any other issues :slightly_smiling_face:
