### ISSUE TITLE
LKE node pool taintl

### ISSUE THREAD

**Issue by n1o** [linode/terraform-provider-linode#752]
Hi,
trying to find out if It is possible to place a [taint](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) on a node pool.

Cheers

**Comment by lgarber-akamai** [comment]
Hi there @n1o !

At the moment, node pools can not be directly tainted through the Linode API or Terraform provider, but this functionality is on our radar internally.

As a workaround, you could try using `kubectl` with a `local-exec` provisioner:

```terraform
resource "linode_lke_cluster" "my-cluster" {
  label       = "my-cluster"
  k8s_version = "1.25"
  region      = "us-southeast"

  pool {
    type  = "g6-standard-2"
    count = 2
  }
  pool {
    type  = "g6-standard-1"
    count = 2
  }
}

resource "null_resource" "apply_pool_taints" {
  # We want to taint all nodes in the first node pool
  for_each = toset(linode_lke_cluster.my-cluster.pool[0].nodes[*].id)

  provisioner "local-exec" {
    environment = {
      KUBECONFIG = local_file.kubeconfig.filename
    }
    command = "kubectl taint nodes --overwrite lke${linode_lke_cluster.my-cluster.id}-${each.value} key=value:NoSchedule"
  }
}

resource "local_file" "kubeconfig" {
  content_base64 = linode_lke_cluster.my-cluster.kubeconfig
  filename = "./kubeconfig.yml"
}
```

To simplify this implementation further, you could move the taint `null_resource` into a separate [module](https://developer.hashicorp.com/terraform/language/modules).

Hope this helps! 🙂

**Comment by n1o** [comment]
Hi @lgarber-akamai.

Thank you for the answer, unfortunately this is not helpful for my use case. I normally run kubernetes in GCP, and by placing an taint on my node pool I can keep them drained, an only trigger a scaleup when a pod is submited with the appropriate tolleration.
