### ISSUE TITLE
[Bug]: 2.1.0 checksum error

### ISSUE THREAD

**Issue by akerl** [linode/terraform-provider-linode#826]
### Terraform Version

Terraform v1.4.6 on darwin_arm64

### Linode Provider Version

version = "2.1.0"

### Effected Terraform Resources

all

### Terraform Config Files

terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "2.1.0"
    }
  }
}

### Expected Behavior

`terraform init` should succeed

### Actual Behavior

`terraform init` fails with a checksum error:

```
❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding linode/linode versions matching "2.1.0"...
- Installing linode/linode v2.1.0...
╷
│ Error: Failed to install provider
│
│ Error while installing linode/linode v2.1.0: checksum list has unexpected SHA-256 hash 53004073803972c4d52e5f9e50135dfd04aeba00e91ccd9fcc045b885d3c7e6d (expected
│ 1073306d7ff302cfc7f509c79b94b95e4819440dc5936db38b047baa5085f0d2)
```

### Steps to Reproduce

Use the v2.1.0 provider:

```
terraform {
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "2.1.0"
    }
  }
}
```

Run `terraform init`

**Comment by lgarber-akamai** [comment]
Thanks for the report @akerl!
This appears to be the result of an issue that occurred while building binaries for our previous release. I've cut a new release `v2.1.1` which should hopefully resolve this issue.

**Comment by akerl** [comment]
Confirmed! Looking good w/ the new version:

```
❯ tf init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding linode/linode versions matching "2.1.1"...
- Installing linode/linode v2.1.1...
- Installed linode/linode v2.1.1 (signed by a HashiCorp partner, key ID F4E6BBD0EA4FE463)
```

Thanks for the quick fix!
