### ISSUE TITLE
[Feature]: Iterable linode_config devices structure

### ISSUE THREAD

**Issue by codedumper** [linode/terraform-provider-linode#860]
### Description

Currently, there is no way to define dynamically the block name in terraform. 
As the "devices" block has a different nested block name for each disk, it makes impossible to iterate and build disk dynamically. 

With the following variable, it is impossible to generate dynamically the nested devices blocks:
```hcl
variable "disks" {
  type = map(
    object({
      device_name = string
      size        = number
      filesystem  = string
    })
  )

  default = {
    root = {
      device_name = string
      filesystem  = "ext4"
      size        = 4000
    },
    swap = {
      device_name = string
      filesystem  = "swap"
      size        = 512
    }
  }
}
```

### New or Affected Terraform Resources

linode_config

### Potential Terraform Configuration

Here is the proposal for the new devices structure:
```hcl
variable "disks" {
  type = map(
    object({
      device_name = string
      size        = number
      filesystem  = string
    })
  )

  default = {
    root = {
      device_name = string
      filesystem  = "ext4"
      size        = 4000
    },
    swap = {
      device_name = string
      filesystem  = "swap"
      size        = 512
    }
  }
}

resource "linode_instance_disk" "disks" {
  for_each = var.disks
  label    = each.key

  # ...
  linode_id  = linode_instance.instance.id // from another declaration
  size       = each.value.size
  filesystem       = each.value.filesystem


resource "linode_instance_config" "config" {
  label       = "example"
  # ...
  root_device = var.disks["root"].device_name

  dynamic "device" {
    for_each = linode_disks
    content {
        device = each.value.device_name
                device_name = each.value.device_name
                disk_id = linode_instance_disk.disks[each.key].id
    }
  }
}
```
As there is no more nested structure, it is way simpler to declare. All devices blocks will be available as an iterable array in the provider. It basically reproduce the same way you used for interfaces.

**Comment by lgarber-akamai** [comment]
Hello @codedumper, thanks for the feature request!

This nested block structure is something we're looking to move away from as we move forward with provider development due to its complexity to work with.

To keep the implementation consistent with the [Linode API](https://www.linode.com/docs/api/linode-instances/#configuration-profile-create__request-body-schema) and to keep device mapping explicit, how would you feel about some sort of `device_map` attribute that allows users to map a key (e.g. `sda`) to a device object? This solution should still allow for the dynamic mapping of disks without the need for dynamic blocks.

**Comment by codedumper** [comment]
Here is the issue with the nested block with different keys. 
Your current structure requires the following code to work, but it's not supported.
```
dynamic "devices" {
  for_each = var.disks
  content {
    dynamic "${each.value.device_map}".  <--- Only static string supported - Not currently supported by terraform
      for_each = var.disks
       content {
       ....
      }
   }
}
```

Adding the device_map field will not help. We can't use a nested dynamic block name. 
The issue is not at field level, but at block name level.

**Comment by codedumper** [comment]
That issue is directly related to the static definition into the provider:
```
var devicesSchema = map[string]*schema.Schema{
	"sda": {
		Type:        schema.TypeList,
		Description: deviceDescription,
		MaxItems:    1,
		Optional:    true,
		Elem:        &schema.Resource{Schema: deviceSchema},
	},....
```
using de device block without nested block will generate a dynamic array instead of static mapping.
To maintain compatibility you can support both approach (but only one at a time).
devices array can easily be mapped to device map.

**Comment by lgarber-akamai** [comment]
@codedumper It looks like I might not have communicated my proposed solution well 🙂 

Here's an example of what I mean:

```terraform
locals {
  my_disk_ids = [123, 456, 789]
  device_names = ["sda", "sdb", "sdc"]
}

resource "linode_instance_config" "config" {
  linode_id = 12345
  label = "example"
  ...

  device_map = {
    for i, id in local.my_disk_ids : local.device_names[i] => {
      disk_id = id
    }
  }
}
```

**Comment by codedumper** [comment]
Replacing the block and nested blocks by an variable does the tricks.
`
device_map = map(object({ disk_id=number}))
`

Variables are way easier to handle. 
Thanks for the reactivity @lgarber-akamai

**Comment by lgarber-akamai** [comment]
Perfect! I'll add a ticket to our internal tracker to add this functionality and get back to you when I have any updates.
