### ISSUE TITLE
[Bug]: circular linode_id definition with linode_disk and linode_config 

### ISSUE THREAD

**Issue by codedumper** [linode/terraform-provider-linode#871]
### Terraform Version

Terraform v1.4.6 on darwin_arm64

### Linode Provider Version

+ provider registry.terraform.io/linode/linode v2.3.0

### Effected Terraform Resources

linode_disk
linode_config

### Terraform Config Files

```
resource "linode_instance_disk" "disks" {
for_each=
...
  linode_id        = resource.linode.id
 }
 
 resource "linode_instance_config" "config" {
...
  devices {
    "sda" {
        disk_id = linode_instance_disk.disks["sda"].id
    }
}
```

### Debug Output

without linode_id :
│ The argument "linode_id" is required, but no definition was found.
linode_id is required.

### Expected Behavior

In a setup using linode_config with disk definition, linode_id should not be required on linode_disk instances.

### Actual Behavior

linode_id is required in linode_disk instances even if disk are defined in linode_config.

### Steps to Reproduce

create a linode_disk
create a linode_config with a disk block.
remove the linode_id from disk.

**Comment by codedumper** [comment]
workaround is to define both linode_id from the same source (usually linode_instance.instance.id.

**Comment by zliang-akamai** [comment]
In the provider implementation, it would be required to have a `linode_id` to create a disk or a config with Linode API v4. I am not sure if there is a way to get around this, but I think having an single source of `linode_id` may be the right way to solve this.

If your Linode instances(s) is created outside of TF managed infra, I think you may want to try importing resource, https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#import

**Comment by frissenm** [comment]
> If your Linode instances(s) is created outside of TF managed infra, I think you might want to try importing it, https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#import

It looks as though the import of linode_instance_config <instance ID>,<config ID> and linode_instance_disk <instance ID>, <disk ID> results in:
"the import command expects two arguments" 

and in terraform plan:
[ERROR] provider.terraform-provider-linode_v2.6.0: Response contains error diagnostic: diagnostic_detail= diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=registry.terraform.io/linode/linode tf_req_id=8e2db9ba-e8d9-ec4f-3027-98cd08d65425 tf_rpc=ImportResourceState tf_resource_type=linode_instance_disk @caller=github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_summary="The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers.

I've seen this with other providers as well, can't find this issue in this repo though. Is this related? (not a developer, only a user ;-))

**Comment by zliang-akamai** [comment]
Hi @frissenm,
Thank you for reporting this! I will investigate it.

**Comment by zliang-akamai** [comment]
@frissenm 
May I have a sample TF config that could trigger these errors?

**Comment by zliang-akamai** [comment]
Hi @frissenm,
I couldn't reproduce the issue you mentioned. The correct format to import a disk is: `<linode_id>,<disk_id>`, for example: `"3476421,556435"`. Can you double check it and see if it is working as expected?

I think we have solved the concern reported in this (original) issue. If you are still experiencing any issue, you are welcome to open a new issue on our GitHub. Thank you!

**Comment by codedumper** [comment]
I think the issue is misunderstood:
- A linode_instance_config requires a linode id and a disk id
- A linode_instance_disk requires a linode id (also defined through linode_instance_config)

The fact is:
- You are requiring the linode id in linode_instance_disk for linode instantiation without linode_instance_config
- But linode id in linode_instance_disk should be deducted from linode config when  linode_instance_config is used.

Why ? because of inconsistency. Technically we could have a different linode id in linode_instance_disk and linode_instance_config.
