### ISSUE TITLE
[Bug]: Unable to add simple Accept Out Drop In simple firewall rules

### ISSUE THREAD

**Issue by codedumper** [linode/terraform-provider-linode#881]
### Terraform Version

Terraform v1.4.6 on darwin_arm64

### Linode Provider Version

v2.4.0

### Effected Terraform Resources

linode_firewall

### Terraform Config Files

No real code here

### Debug Output

When you try to do the same with provider the API, you are unable to create that firewall with no rule.
- Error: cannot create firewall without at least one inbound or outbound rule

### Expected Behavior

Create a linode_firewall with only inbound and outbound policy without rule.

### Actual Behavior

**Unable to create that firewall with no rule**
Using UI, you can create a simple firewall with just policy and no rule like: 
Outbound: ACCEPT, Inbound: DROP 

When you try to do the same with provider the API, you are unable to create that firewall with no rule.
But, it is possible using terraform, to create the firewall with one rule, remove the rule in terraform code, and then re-apply and delete the rule.

### Steps to Reproduce

```
resource "linode_firewall" "name" {
  label           = "all_out_no_in_firewall"
  linodes         = var.linode_ids
  inbound_policy  = "DROP
  outbound_policy = "ACCEPT"
}
```

**Comment by lgarber-akamai** [comment]
Thanks for the report!

As far as I can tell, we'll just need to populate the `inbound` and `outbound` fields with empty lists on firewall creation if no rules are specified by the user.

 I'll create a ticket in our internal tracker to address this and let you know when we have any updates to share 🙂
