### ISSUE TITLE
[Feature]: Create vlan with dynamic ips from custom ip range

### ISSUE THREAD

**Issue by ajprok** [linode/terraform-provider-linode#958]
### Description

Could you please create a **vlan resource** with **optional ip range** which can **dynamically** provide ips to new instances using that vlan.
Thank you

### New or Affected Terraform Resources

linode_vlan

### Potential Terraform Configuration

resource "linode_vlan" "example" {
  name     = "example-project-network"
  region   = "ap-west"
  ip_range = "10.10.10.0/24"
}

**Comment by jriddle-linode** [comment]
I believe what you're looking for is supplied in the [linode_instance_config](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance_config#interface) resource.

```yaml
resource "linode_instance_config" "my-config" {
  linode_id = linode_instance.my-instance.id
  label = "my-config"

  interface {
    purpose = "vlan"
    label = "my-vlan"
    ipam_address = "10.0.0.2/24"
  }
}
```

**Comment by ajprok** [comment]
Thank you for your time.

However, I was thinking more along the lines of linode providing a dynamically assigned ipam_address from the ip_range, instead of us assiging an ipam_address like "10.0.0.2/24".

**Comment by ajprok** [comment]
@jriddle-linode Thank you for your time.

However, I was thinking more along the lines of linode providing a dynamically assigned ipam_address from the ip_range, instead of us assiging an ipam_address like "10.0.0.2/24".
