### ISSUE TITLE
[Bug]: incorrect maintenance window for mysql database

### ISSUE THREAD

**Issue by raisedadead** [linode/terraform-provider-linode#982]
### Terraform Version

Terraform v1.5.5 on darwin_arm64

### Linode Provider Version

2.5.2

### Effected Terraform Resources

linode_database_mysql

### Terraform Config Files

```hcl
resource "linode_database_mysql" "mydb" {
  ...

  # Do maintenance on every 2nd Saturday at 2am UTC, maximum maintenance window of 1 hour.
  updates {
    day_of_week   = "saturday"
    duration      = 1
    frequency     = "monthly"
    hour_of_day   = 2
    week_of_month = 2
  }
}
```

### Expected Behavior

The Cloud Manager UI should show the correct date, from the example is should be "2nd Saturday at 2am UTC, maximum maintenance window of 1 hour."

### Actual Behavior

<img width="1095" alt="image" src="https://github.com/linode/terraform-provider-linode/assets/1884376/58e05d04-4004-4118-87fb-43f79167c530">

It's off by a day, and the hour is off too? 

### Steps to Reproduce

1. Create a DB using the snippet as an example. 
2. Go to Cloud Manager UI and compare the settings.

**Comment by zliang-akamai** [comment]
Thanks for reporting this! A fix is in progress.

**Comment by zliang-akamai** [comment]
This has been fixed in https://github.com/linode/terraform-provider-linode/pull/1016
