### ISSUE TITLE
[Bug]: Error when create linode server with custom image and StackScripts

### ISSUE THREAD

**Issue by wannamilk** [linode/terraform-provider-linode#991]
### Terraform Version

0.12.31

### Linode Provider Version

2.7.0

### Effected Terraform Resources

linode_instance
linode_stackscript

### Expected Behavior

Terraform creates linode_instance based on custom image and stackscript with images = ["any/all"]

### Actual Behavior

Error: Error creating a Linode Instance: [400] StackScripts must be associated with at least one image or distro

### Steps to Reproduce

1. Create custom image
2. Create stackscript with images = ["any/all"]
3. Create resource linode_instance with stackscript and custom image

**Comment by wannamilk** [comment]
and the error
`Error: Error creating a Linode Instance: [400] StackScripts must be associated with at least one image or distro

  on doorman-colo.tf line 1, in resource "linode_instance" "myserver-linode":
   1: resource "linode_instance" "myserver-linode" {`

**Comment by lgarber-akamai** [comment]
> @lgarber-akamai Sure! Custom image has been created manually
> 
> ```
> resource "linode_instance" "myserver-linode" {
>   count  = 2
>   label  = "myserver-linode-${count.index + 1}"
>   region = var.linode_region
>   type       = "g6-dedicated-4"
>   private_ip = false
> 
>   stackscript_id = linode_stackscript.myserver-linode.id
>   stackscript_data = {
>    "HOSTNAME" = "myserver-linode-${count.index + 1}.${var.linode_region}-nj.com"
>   }
> 
>   group = "myserver"
>   tags = [
>     "myserver-linode"
>   ]
> }
> 
> resource "linode_instance_disk" "myserver-linode" {
>   count     = length(linode_instance.myserver-linode)
>   label     = "boot"
>   linode_id = linode_instance.myserver-linode[count.index].id
>   size = 163840
> 
>   authorized_keys = [
>     ...
>   ]
>   image = "private/999999"
> }
> 
> resource "linode_instance_config" "myserver-linode" {
>   count     = length(linode_instance.myserver-linode)
>   label     = "boot_config"
>   linode_id = linode_instance.myserver-linode[count.index].id
> 
>   devices {
>     sda {
>       disk_id = linode_instance_disk.myserver-linode[count.index].id
>     }
>   }
> 
>   helpers {
>     network = false
>   }
> 
>   interface {
>     purpose = "public"
>   }
> 
>   interface {
>     purpose      = "vlan"
>     label        = "VLAN-100"
>     ipam_address = "10.9.0.1/20"
>   }
> 
>   root_device = "/dev/sda"
>   booted      = true
> }
> 
> resource "linode_stackscript" "myserver-linode" {
>   label       = "myserver-linode"
>   description = ""
>   script      = <<EOF
> #!/bin/bash
> # <UDF name="HOSTNAME" label="Hostname for server" example="" default="">
> 
> echo $HOSTNAME
> 
> EOF
> 
>   images = ["any/all"]
> }
> ```

@wannamilk Thanks for the extra info! 

When creating instances with custom disk configurations, StackScript-related fields should be declared at the disk level rather than at the instance level. Could you try moving the `stackscript_id` and `stackscript_data` lines from the `linode_instance` resource into the `linode_instance_disk` resource?

**Comment by wannamilk** [comment]
@lgarber-akamai Yes, it's working! Sorry for false bug opened. It may be useful to include this information here
https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#stackscript_id

Thank you for your help, I will close this ticket

**Comment by lgarber-akamai** [comment]
> @lgarber-akamai Yes, it's working! Sorry for false bug opened. It may be useful to include this information here https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#stackscript_id
> 
> Thank you for your help, I will close this ticket

@wannamilk No worries, happy to help! I'll see if we can update our documentation to make this functionality a bit more clear.
